// Code generated by gen-svg; DO NOT EDIT.

package svg

import (
	"strings"

	"github.com/plainkit/html"
)

// EllipseAttrs holds the attributes for the ellipse SVG element
type EllipseAttrs struct {
	SvgGlobal SvgGlobalAttrs
	Cx        string
	Cy        string
	Rx        string
	Ry        string
}

// EllipseArg interface for ellipse element arguments
type EllipseArg interface {
	applyEllipse(*EllipseAttrs, *[]html.Component)
}

// defaultEllipseAttrs creates default attributes for ellipse
func defaultEllipseAttrs() *EllipseAttrs {
	return &EllipseAttrs{
		SvgGlobal: SvgGlobalAttrs{},
	}
}

// Ellipse creates an SVG ellipse element
func Ellipse(args ...EllipseArg) html.Node {
	a := defaultEllipseAttrs()
	var kids []html.Component
	for _, ar := range args {
		ar.applyEllipse(a, &kids)
	}
	return html.Node{
		Tag:   "ellipse",
		Attrs: a,
		Kids:  kids,
	}
}

// Global applies global SVG attributes to ellipse
func (g Global) applyEllipse(a *EllipseAttrs, _ *[]html.Component) {
	g.do(&a.SvgGlobal)
}

// CxOpt applies to Ellipse
func (o CxOpt) applyEllipse(a *EllipseAttrs, _ *[]html.Component) {
	a.Cx = o.v
}

// CyOpt applies to Ellipse
func (o CyOpt) applyEllipse(a *EllipseAttrs, _ *[]html.Component) {
	a.Cy = o.v
}

// RxOpt applies to Ellipse
func (o RxOpt) applyEllipse(a *EllipseAttrs, _ *[]html.Component) {
	a.Rx = o.v
}

// RyOpt applies to Ellipse
func (o RyOpt) applyEllipse(a *EllipseAttrs, _ *[]html.Component) {
	a.Ry = o.v
}

// writeAttrs writes the SVG attributes to the string builder
func (a *EllipseAttrs) writeAttrs(sb *strings.Builder) {
	WriteSvgGlobal(sb, &a.SvgGlobal)
	if a.Cx != "" {
		SvgAttr(sb, "cx", a.Cx)
	}
	if a.Cy != "" {
		SvgAttr(sb, "cy", a.Cy)
	}
	if a.Rx != "" {
		SvgAttr(sb, "rx", a.Rx)
	}
	if a.Ry != "" {
		SvgAttr(sb, "ry", a.Ry)
	}
}
