// Code generated by gen-svg; DO NOT EDIT.

package svg

import (
	"strings"

	"github.com/plainkit/html"
)

// FeTurbulenceAttrs holds the attributes for the feTurbulence SVG element
type FeTurbulenceAttrs struct {
	SvgGlobal                  SvgGlobalAttrs
	AlignmentBaseline          string
	BaseFrequency              string
	BaselineShift              string
	Clip                       string
	ClipPath                   string
	ClipRule                   string
	Color                      string
	ColorInterpolation         string
	ColorInterpolationFilters  string
	ColorProfile               string
	ColorRendering             string
	Cursor                     string
	Direction                  string
	Display                    string
	DominantBaseline           string
	EnableBackground           string
	Fill                       string
	FillOpacity                string
	FillRule                   string
	Filter                     string
	FloodColor                 string
	FloodOpacity               string
	FontFamily                 string
	FontSize                   string
	FontSizeAdjust             string
	FontStretch                string
	FontStyle                  string
	FontVariant                string
	FontWeight                 string
	GlyphOrientationHorizontal string
	GlyphOrientationVertical   string
	Height                     string
	ImageRendering             string
	Kerning                    string
	LetterSpacing              string
	LightingColor              string
	MarkerEnd                  string
	MarkerMid                  string
	MarkerStart                string
	Mask                       string
	NumOctaves                 string
	Opacity                    string
	Overflow                   string
	PointerEvents              string
	Result                     string
	Seed                       string
	ShapeRendering             string
	StitchTiles                string
	StopColor                  string
	StopOpacity                string
	Stroke                     string
	StrokeDasharray            string
	StrokeDashoffset           string
	StrokeLinecap              string
	StrokeLinejoin             string
	StrokeMiterlimit           string
	StrokeOpacity              string
	StrokeWidth                string
	TextAnchor                 string
	TextDecoration             string
	TextRendering              string
	Type                       string
	UnicodeBidi                string
	Visibility                 string
	Width                      string
	WordSpacing                string
	WritingMode                string
	X                          string
	Y                          string
}

// FeTurbulenceArg interface for feTurbulence element arguments
type FeTurbulenceArg interface {
	applyFeTurbulence(*FeTurbulenceAttrs, *[]html.Component)
}

// defaultFeTurbulenceAttrs creates default attributes for feTurbulence
func defaultFeTurbulenceAttrs() *FeTurbulenceAttrs {
	return &FeTurbulenceAttrs{
		SvgGlobal: SvgGlobalAttrs{},
	}
}

// FeTurbulence creates an SVG feTurbulence element
func FeTurbulence(args ...FeTurbulenceArg) html.Node {
	a := defaultFeTurbulenceAttrs()
	var kids []html.Component
	for _, ar := range args {
		ar.applyFeTurbulence(a, &kids)
	}
	return html.Node{
		Tag:   "feTurbulence",
		Attrs: a,
		Kids:  kids,
	}
}

// Global applies global SVG attributes to feTurbulence
func (g Global) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	g.do(&a.SvgGlobal)
}

// AlignmentBaselineOpt applies to FeTurbulence
func (o AlignmentBaselineOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.AlignmentBaseline = o.v
}

// BaseFrequencyOpt applies to FeTurbulence
func (o BaseFrequencyOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.BaseFrequency = o.v
}

// BaselineShiftOpt applies to FeTurbulence
func (o BaselineShiftOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.BaselineShift = o.v
}

// ClipOpt applies to FeTurbulence
func (o ClipOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.Clip = o.v
}

// ClipPathOpt applies to FeTurbulence
func (o ClipPathOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.ClipPath = o.v
}

// ClipRuleOpt applies to FeTurbulence
func (o ClipRuleOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.ClipRule = o.v
}

// ColorOpt applies to FeTurbulence
func (o ColorOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.Color = o.v
}

// ColorInterpolationOpt applies to FeTurbulence
func (o ColorInterpolationOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.ColorInterpolation = o.v
}

// ColorInterpolationFiltersOpt applies to FeTurbulence
func (o ColorInterpolationFiltersOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.ColorInterpolationFilters = o.v
}

// ColorProfileOpt applies to FeTurbulence
func (o ColorProfileOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.ColorProfile = o.v
}

// ColorRenderingOpt applies to FeTurbulence
func (o ColorRenderingOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.ColorRendering = o.v
}

// CursorOpt applies to FeTurbulence
func (o CursorOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.Cursor = o.v
}

// DirectionOpt applies to FeTurbulence
func (o DirectionOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.Direction = o.v
}

// DisplayOpt applies to FeTurbulence
func (o DisplayOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.Display = o.v
}

// DominantBaselineOpt applies to FeTurbulence
func (o DominantBaselineOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.DominantBaseline = o.v
}

// EnableBackgroundOpt applies to FeTurbulence
func (o EnableBackgroundOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.EnableBackground = o.v
}

// FillOpt applies to FeTurbulence
func (o FillOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.Fill = o.v
}

// FillOpacityOpt applies to FeTurbulence
func (o FillOpacityOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.FillOpacity = o.v
}

// FillRuleOpt applies to FeTurbulence
func (o FillRuleOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.FillRule = o.v
}

// FilterOpt applies to FeTurbulence
func (o FilterOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.Filter = o.v
}

// FloodColorOpt applies to FeTurbulence
func (o FloodColorOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.FloodColor = o.v
}

// FloodOpacityOpt applies to FeTurbulence
func (o FloodOpacityOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.FloodOpacity = o.v
}

// FontFamilyOpt applies to FeTurbulence
func (o FontFamilyOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.FontFamily = o.v
}

// FontSizeOpt applies to FeTurbulence
func (o FontSizeOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.FontSize = o.v
}

// FontSizeAdjustOpt applies to FeTurbulence
func (o FontSizeAdjustOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.FontSizeAdjust = o.v
}

// FontStretchOpt applies to FeTurbulence
func (o FontStretchOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.FontStretch = o.v
}

// FontStyleOpt applies to FeTurbulence
func (o FontStyleOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.FontStyle = o.v
}

// FontVariantOpt applies to FeTurbulence
func (o FontVariantOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.FontVariant = o.v
}

// FontWeightOpt applies to FeTurbulence
func (o FontWeightOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.FontWeight = o.v
}

// GlyphOrientationHorizontalOpt applies to FeTurbulence
func (o GlyphOrientationHorizontalOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.GlyphOrientationHorizontal = o.v
}

// GlyphOrientationVerticalOpt applies to FeTurbulence
func (o GlyphOrientationVerticalOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.GlyphOrientationVertical = o.v
}

// HeightOpt applies to FeTurbulence
func (o HeightOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.Height = o.v
}

// ImageRenderingOpt applies to FeTurbulence
func (o ImageRenderingOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.ImageRendering = o.v
}

// KerningOpt applies to FeTurbulence
func (o KerningOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.Kerning = o.v
}

// LetterSpacingOpt applies to FeTurbulence
func (o LetterSpacingOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.LetterSpacing = o.v
}

// LightingColorOpt applies to FeTurbulence
func (o LightingColorOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.LightingColor = o.v
}

// MarkerEndOpt applies to FeTurbulence
func (o MarkerEndOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.MarkerEnd = o.v
}

// MarkerMidOpt applies to FeTurbulence
func (o MarkerMidOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.MarkerMid = o.v
}

// MarkerStartOpt applies to FeTurbulence
func (o MarkerStartOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.MarkerStart = o.v
}

// MaskOpt applies to FeTurbulence
func (o MaskOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.Mask = o.v
}

// NumOctavesOpt applies to FeTurbulence
func (o NumOctavesOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.NumOctaves = o.v
}

// OpacityOpt applies to FeTurbulence
func (o OpacityOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.Opacity = o.v
}

// OverflowOpt applies to FeTurbulence
func (o OverflowOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.Overflow = o.v
}

// PointerEventsOpt applies to FeTurbulence
func (o PointerEventsOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.PointerEvents = o.v
}

// ResultOpt applies to FeTurbulence
func (o ResultOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.Result = o.v
}

// SeedOpt applies to FeTurbulence
func (o SeedOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.Seed = o.v
}

// ShapeRenderingOpt applies to FeTurbulence
func (o ShapeRenderingOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.ShapeRendering = o.v
}

// StitchTilesOpt applies to FeTurbulence
func (o StitchTilesOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.StitchTiles = o.v
}

// StopColorOpt applies to FeTurbulence
func (o StopColorOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.StopColor = o.v
}

// StopOpacityOpt applies to FeTurbulence
func (o StopOpacityOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.StopOpacity = o.v
}

// StrokeOpt applies to FeTurbulence
func (o StrokeOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.Stroke = o.v
}

// StrokeDasharrayOpt applies to FeTurbulence
func (o StrokeDasharrayOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.StrokeDasharray = o.v
}

// StrokeDashoffsetOpt applies to FeTurbulence
func (o StrokeDashoffsetOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.StrokeDashoffset = o.v
}

// StrokeLinecapOpt applies to FeTurbulence
func (o StrokeLinecapOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.StrokeLinecap = o.v
}

// StrokeLinejoinOpt applies to FeTurbulence
func (o StrokeLinejoinOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.StrokeLinejoin = o.v
}

// StrokeMiterlimitOpt applies to FeTurbulence
func (o StrokeMiterlimitOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.StrokeMiterlimit = o.v
}

// StrokeOpacityOpt applies to FeTurbulence
func (o StrokeOpacityOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.StrokeOpacity = o.v
}

// StrokeWidthOpt applies to FeTurbulence
func (o StrokeWidthOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.StrokeWidth = o.v
}

// TextAnchorOpt applies to FeTurbulence
func (o TextAnchorOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.TextAnchor = o.v
}

// TextDecorationOpt applies to FeTurbulence
func (o TextDecorationOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.TextDecoration = o.v
}

// TextRenderingOpt applies to FeTurbulence
func (o TextRenderingOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.TextRendering = o.v
}

// TypeOpt applies to FeTurbulence
func (o TypeOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.Type = o.v
}

// UnicodeBidiOpt applies to FeTurbulence
func (o UnicodeBidiOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.UnicodeBidi = o.v
}

// VisibilityOpt applies to FeTurbulence
func (o VisibilityOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.Visibility = o.v
}

// WidthOpt applies to FeTurbulence
func (o WidthOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.Width = o.v
}

// WordSpacingOpt applies to FeTurbulence
func (o WordSpacingOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.WordSpacing = o.v
}

// WritingModeOpt applies to FeTurbulence
func (o WritingModeOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.WritingMode = o.v
}

// XOpt applies to FeTurbulence
func (o XOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.X = o.v
}

// YOpt applies to FeTurbulence
func (o YOpt) applyFeTurbulence(a *FeTurbulenceAttrs, _ *[]html.Component) {
	a.Y = o.v
}

// writeAttrs writes the SVG attributes to the string builder
func (a *FeTurbulenceAttrs) writeAttrs(sb *strings.Builder) {
	WriteSvgGlobal(sb, &a.SvgGlobal)
	if a.AlignmentBaseline != "" {
		SvgAttr(sb, "alignment-baseline", a.AlignmentBaseline)
	}
	if a.BaseFrequency != "" {
		SvgAttr(sb, "baseFrequency", a.BaseFrequency)
	}
	if a.BaselineShift != "" {
		SvgAttr(sb, "baseline-shift", a.BaselineShift)
	}
	if a.Clip != "" {
		SvgAttr(sb, "clip", a.Clip)
	}
	if a.ClipPath != "" {
		SvgAttr(sb, "clip-path", a.ClipPath)
	}
	if a.ClipRule != "" {
		SvgAttr(sb, "clip-rule", a.ClipRule)
	}
	if a.Color != "" {
		SvgAttr(sb, "color", a.Color)
	}
	if a.ColorInterpolation != "" {
		SvgAttr(sb, "color-interpolation", a.ColorInterpolation)
	}
	if a.ColorInterpolationFilters != "" {
		SvgAttr(sb, "color-interpolation-filters", a.ColorInterpolationFilters)
	}
	if a.ColorProfile != "" {
		SvgAttr(sb, "color-profile", a.ColorProfile)
	}
	if a.ColorRendering != "" {
		SvgAttr(sb, "color-rendering", a.ColorRendering)
	}
	if a.Cursor != "" {
		SvgAttr(sb, "cursor", a.Cursor)
	}
	if a.Direction != "" {
		SvgAttr(sb, "direction", a.Direction)
	}
	if a.Display != "" {
		SvgAttr(sb, "display", a.Display)
	}
	if a.DominantBaseline != "" {
		SvgAttr(sb, "dominant-baseline", a.DominantBaseline)
	}
	if a.EnableBackground != "" {
		SvgAttr(sb, "enable-background", a.EnableBackground)
	}
	if a.Fill != "" {
		SvgAttr(sb, "fill", a.Fill)
	}
	if a.FillOpacity != "" {
		SvgAttr(sb, "fill-opacity", a.FillOpacity)
	}
	if a.FillRule != "" {
		SvgAttr(sb, "fill-rule", a.FillRule)
	}
	if a.Filter != "" {
		SvgAttr(sb, "filter", a.Filter)
	}
	if a.FloodColor != "" {
		SvgAttr(sb, "flood-color", a.FloodColor)
	}
	if a.FloodOpacity != "" {
		SvgAttr(sb, "flood-opacity", a.FloodOpacity)
	}
	if a.FontFamily != "" {
		SvgAttr(sb, "font-family", a.FontFamily)
	}
	if a.FontSize != "" {
		SvgAttr(sb, "font-size", a.FontSize)
	}
	if a.FontSizeAdjust != "" {
		SvgAttr(sb, "font-size-adjust", a.FontSizeAdjust)
	}
	if a.FontStretch != "" {
		SvgAttr(sb, "font-stretch", a.FontStretch)
	}
	if a.FontStyle != "" {
		SvgAttr(sb, "font-style", a.FontStyle)
	}
	if a.FontVariant != "" {
		SvgAttr(sb, "font-variant", a.FontVariant)
	}
	if a.FontWeight != "" {
		SvgAttr(sb, "font-weight", a.FontWeight)
	}
	if a.GlyphOrientationHorizontal != "" {
		SvgAttr(sb, "glyph-orientation-horizontal", a.GlyphOrientationHorizontal)
	}
	if a.GlyphOrientationVertical != "" {
		SvgAttr(sb, "glyph-orientation-vertical", a.GlyphOrientationVertical)
	}
	if a.Height != "" {
		SvgAttr(sb, "height", a.Height)
	}
	if a.ImageRendering != "" {
		SvgAttr(sb, "image-rendering", a.ImageRendering)
	}
	if a.Kerning != "" {
		SvgAttr(sb, "kerning", a.Kerning)
	}
	if a.LetterSpacing != "" {
		SvgAttr(sb, "letter-spacing", a.LetterSpacing)
	}
	if a.LightingColor != "" {
		SvgAttr(sb, "lighting-color", a.LightingColor)
	}
	if a.MarkerEnd != "" {
		SvgAttr(sb, "marker-end", a.MarkerEnd)
	}
	if a.MarkerMid != "" {
		SvgAttr(sb, "marker-mid", a.MarkerMid)
	}
	if a.MarkerStart != "" {
		SvgAttr(sb, "marker-start", a.MarkerStart)
	}
	if a.Mask != "" {
		SvgAttr(sb, "mask", a.Mask)
	}
	if a.NumOctaves != "" {
		SvgAttr(sb, "numOctaves", a.NumOctaves)
	}
	if a.Opacity != "" {
		SvgAttr(sb, "opacity", a.Opacity)
	}
	if a.Overflow != "" {
		SvgAttr(sb, "overflow", a.Overflow)
	}
	if a.PointerEvents != "" {
		SvgAttr(sb, "pointer-events", a.PointerEvents)
	}
	if a.Result != "" {
		SvgAttr(sb, "result", a.Result)
	}
	if a.Seed != "" {
		SvgAttr(sb, "seed", a.Seed)
	}
	if a.ShapeRendering != "" {
		SvgAttr(sb, "shape-rendering", a.ShapeRendering)
	}
	if a.StitchTiles != "" {
		SvgAttr(sb, "stitchTiles", a.StitchTiles)
	}
	if a.StopColor != "" {
		SvgAttr(sb, "stop-color", a.StopColor)
	}
	if a.StopOpacity != "" {
		SvgAttr(sb, "stop-opacity", a.StopOpacity)
	}
	if a.Stroke != "" {
		SvgAttr(sb, "stroke", a.Stroke)
	}
	if a.StrokeDasharray != "" {
		SvgAttr(sb, "stroke-dasharray", a.StrokeDasharray)
	}
	if a.StrokeDashoffset != "" {
		SvgAttr(sb, "stroke-dashoffset", a.StrokeDashoffset)
	}
	if a.StrokeLinecap != "" {
		SvgAttr(sb, "stroke-linecap", a.StrokeLinecap)
	}
	if a.StrokeLinejoin != "" {
		SvgAttr(sb, "stroke-linejoin", a.StrokeLinejoin)
	}
	if a.StrokeMiterlimit != "" {
		SvgAttr(sb, "stroke-miterlimit", a.StrokeMiterlimit)
	}
	if a.StrokeOpacity != "" {
		SvgAttr(sb, "stroke-opacity", a.StrokeOpacity)
	}
	if a.StrokeWidth != "" {
		SvgAttr(sb, "stroke-width", a.StrokeWidth)
	}
	if a.TextAnchor != "" {
		SvgAttr(sb, "text-anchor", a.TextAnchor)
	}
	if a.TextDecoration != "" {
		SvgAttr(sb, "text-decoration", a.TextDecoration)
	}
	if a.TextRendering != "" {
		SvgAttr(sb, "text-rendering", a.TextRendering)
	}
	if a.Type != "" {
		SvgAttr(sb, "type", a.Type)
	}
	if a.UnicodeBidi != "" {
		SvgAttr(sb, "unicode-bidi", a.UnicodeBidi)
	}
	if a.Visibility != "" {
		SvgAttr(sb, "visibility", a.Visibility)
	}
	if a.Width != "" {
		SvgAttr(sb, "width", a.Width)
	}
	if a.WordSpacing != "" {
		SvgAttr(sb, "word-spacing", a.WordSpacing)
	}
	if a.WritingMode != "" {
		SvgAttr(sb, "writing-mode", a.WritingMode)
	}
	if a.X != "" {
		SvgAttr(sb, "x", a.X)
	}
	if a.Y != "" {
		SvgAttr(sb, "y", a.Y)
	}
}
