// Code generated by gen-svg; DO NOT EDIT.
package svg

import (
	"strings"

	"github.com/plainkit/html"
)

type FontFaceFormatAttrs struct {
	html.GlobalAttrs
	String string
}

func FontFaceFormat(attrs FontFaceFormatAttrs, children ...html.Component) html.Node {
	return html.Node{Tag: "font-face-format", Attrs: &attrs, Kids: children}
}

func (a *FontFaceFormatAttrs) writeAttrs(sb *strings.Builder) {
	html.WriteGlobal(sb, &a.GlobalAttrs)
	if a.String != "" {
		html.Attr(sb, "string", a.String)
	}
}
