// Code generated by gen-svg; DO NOT EDIT.

package svg

import (
	"strings"

	"github.com/plainkit/html"
)

// GAttrs holds the attributes for the g SVG element
type GAttrs struct {
	SvgGlobal                  SvgGlobalAttrs
	AlignmentBaseline          string
	BaselineShift              string
	Clip                       string
	ClipPath                   string
	ClipRule                   string
	Color                      string
	ColorInterpolation         string
	ColorInterpolationFilters  string
	ColorProfile               string
	ColorRendering             string
	Cursor                     string
	Direction                  string
	Display                    string
	DominantBaseline           string
	EnableBackground           string
	ExternalResourcesRequired  string
	Fill                       string
	FillOpacity                string
	FillRule                   string
	Filter                     string
	FloodColor                 string
	FloodOpacity               string
	FocusHighlight             string
	Focusable                  bool
	FontFamily                 string
	FontSize                   string
	FontSizeAdjust             string
	FontStretch                string
	FontStyle                  string
	FontVariant                string
	FontWeight                 string
	GlyphOrientationHorizontal string
	GlyphOrientationVertical   string
	ImageRendering             string
	Kerning                    string
	LetterSpacing              string
	LightingColor              string
	MarkerEnd                  string
	MarkerMid                  string
	MarkerStart                string
	Mask                       string
	NavDown                    string
	NavDownLeft                string
	NavDownRight               string
	NavLeft                    string
	NavNext                    string
	NavPrev                    string
	NavRight                   string
	NavUp                      string
	NavUpLeft                  string
	NavUpRight                 string
	Opacity                    string
	Overflow                   string
	PointerEvents              string
	RequiredExtensions         string
	RequiredFeatures           string
	RequiredFonts              string
	RequiredFormats            string
	ShapeRendering             string
	StopColor                  string
	StopOpacity                string
	Stroke                     string
	StrokeDasharray            string
	StrokeDashoffset           string
	StrokeLinecap              string
	StrokeLinejoin             string
	StrokeMiterlimit           string
	StrokeOpacity              string
	StrokeWidth                string
	SystemLanguage             string
	TextAnchor                 string
	TextDecoration             string
	TextRendering              string
	Transform                  string
	UnicodeBidi                string
	Visibility                 string
	WordSpacing                string
	WritingMode                string
}

// GArg interface for g element arguments
type GArg interface {
	applyG(*GAttrs, *[]html.Component)
}

// defaultGAttrs creates default attributes for g
func defaultGAttrs() *GAttrs {
	return &GAttrs{
		SvgGlobal: SvgGlobalAttrs{},
	}
}

// G creates an SVG g element
func G(args ...GArg) html.Node {
	a := defaultGAttrs()
	var kids []html.Component
	for _, ar := range args {
		ar.applyG(a, &kids)
	}
	return html.Node{
		Tag:   "g",
		Attrs: a,
		Kids:  kids,
	}
}

// Global applies global SVG attributes to g
func (g Global) applyG(a *GAttrs, _ *[]html.Component) {
	g.do(&a.SvgGlobal)
}

// AlignmentBaselineOpt applies to G
func (o AlignmentBaselineOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.AlignmentBaseline = o.v
}

// BaselineShiftOpt applies to G
func (o BaselineShiftOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.BaselineShift = o.v
}

// ClipOpt applies to G
func (o ClipOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.Clip = o.v
}

// ClipPathOpt applies to G
func (o ClipPathOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.ClipPath = o.v
}

// ClipRuleOpt applies to G
func (o ClipRuleOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.ClipRule = o.v
}

// ColorOpt applies to G
func (o ColorOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.Color = o.v
}

// ColorInterpolationOpt applies to G
func (o ColorInterpolationOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.ColorInterpolation = o.v
}

// ColorInterpolationFiltersOpt applies to G
func (o ColorInterpolationFiltersOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.ColorInterpolationFilters = o.v
}

// ColorProfileOpt applies to G
func (o ColorProfileOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.ColorProfile = o.v
}

// ColorRenderingOpt applies to G
func (o ColorRenderingOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.ColorRendering = o.v
}

// CursorOpt applies to G
func (o CursorOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.Cursor = o.v
}

// DirectionOpt applies to G
func (o DirectionOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.Direction = o.v
}

// DisplayOpt applies to G
func (o DisplayOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.Display = o.v
}

// DominantBaselineOpt applies to G
func (o DominantBaselineOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.DominantBaseline = o.v
}

// EnableBackgroundOpt applies to G
func (o EnableBackgroundOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.EnableBackground = o.v
}

// ExternalResourcesRequiredOpt applies to G
func (o ExternalResourcesRequiredOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.ExternalResourcesRequired = o.v
}

// FillOpt applies to G
func (o FillOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.Fill = o.v
}

// FillOpacityOpt applies to G
func (o FillOpacityOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.FillOpacity = o.v
}

// FillRuleOpt applies to G
func (o FillRuleOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.FillRule = o.v
}

// FilterOpt applies to G
func (o FilterOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.Filter = o.v
}

// FloodColorOpt applies to G
func (o FloodColorOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.FloodColor = o.v
}

// FloodOpacityOpt applies to G
func (o FloodOpacityOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.FloodOpacity = o.v
}

// FocusHighlightOpt applies to G
func (o FocusHighlightOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.FocusHighlight = o.v
}

// FocusableOpt applies to G
func (o FocusableOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.Focusable = true
}

// FontFamilyOpt applies to G
func (o FontFamilyOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.FontFamily = o.v
}

// FontSizeOpt applies to G
func (o FontSizeOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.FontSize = o.v
}

// FontSizeAdjustOpt applies to G
func (o FontSizeAdjustOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.FontSizeAdjust = o.v
}

// FontStretchOpt applies to G
func (o FontStretchOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.FontStretch = o.v
}

// FontStyleOpt applies to G
func (o FontStyleOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.FontStyle = o.v
}

// FontVariantOpt applies to G
func (o FontVariantOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.FontVariant = o.v
}

// FontWeightOpt applies to G
func (o FontWeightOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.FontWeight = o.v
}

// GlyphOrientationHorizontalOpt applies to G
func (o GlyphOrientationHorizontalOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.GlyphOrientationHorizontal = o.v
}

// GlyphOrientationVerticalOpt applies to G
func (o GlyphOrientationVerticalOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.GlyphOrientationVertical = o.v
}

// ImageRenderingOpt applies to G
func (o ImageRenderingOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.ImageRendering = o.v
}

// KerningOpt applies to G
func (o KerningOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.Kerning = o.v
}

// LetterSpacingOpt applies to G
func (o LetterSpacingOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.LetterSpacing = o.v
}

// LightingColorOpt applies to G
func (o LightingColorOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.LightingColor = o.v
}

// MarkerEndOpt applies to G
func (o MarkerEndOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.MarkerEnd = o.v
}

// MarkerMidOpt applies to G
func (o MarkerMidOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.MarkerMid = o.v
}

// MarkerStartOpt applies to G
func (o MarkerStartOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.MarkerStart = o.v
}

// MaskOpt applies to G
func (o MaskOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.Mask = o.v
}

// NavDownOpt applies to G
func (o NavDownOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.NavDown = o.v
}

// NavDownLeftOpt applies to G
func (o NavDownLeftOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.NavDownLeft = o.v
}

// NavDownRightOpt applies to G
func (o NavDownRightOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.NavDownRight = o.v
}

// NavLeftOpt applies to G
func (o NavLeftOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.NavLeft = o.v
}

// NavNextOpt applies to G
func (o NavNextOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.NavNext = o.v
}

// NavPrevOpt applies to G
func (o NavPrevOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.NavPrev = o.v
}

// NavRightOpt applies to G
func (o NavRightOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.NavRight = o.v
}

// NavUpOpt applies to G
func (o NavUpOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.NavUp = o.v
}

// NavUpLeftOpt applies to G
func (o NavUpLeftOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.NavUpLeft = o.v
}

// NavUpRightOpt applies to G
func (o NavUpRightOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.NavUpRight = o.v
}

// OpacityOpt applies to G
func (o OpacityOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.Opacity = o.v
}

// OverflowOpt applies to G
func (o OverflowOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.Overflow = o.v
}

// PointerEventsOpt applies to G
func (o PointerEventsOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.PointerEvents = o.v
}

// RequiredExtensionsOpt applies to G
func (o RequiredExtensionsOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.RequiredExtensions = o.v
}

// RequiredFeaturesOpt applies to G
func (o RequiredFeaturesOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.RequiredFeatures = o.v
}

// RequiredFontsOpt applies to G
func (o RequiredFontsOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.RequiredFonts = o.v
}

// RequiredFormatsOpt applies to G
func (o RequiredFormatsOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.RequiredFormats = o.v
}

// ShapeRenderingOpt applies to G
func (o ShapeRenderingOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.ShapeRendering = o.v
}

// StopColorOpt applies to G
func (o StopColorOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.StopColor = o.v
}

// StopOpacityOpt applies to G
func (o StopOpacityOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.StopOpacity = o.v
}

// StrokeOpt applies to G
func (o StrokeOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.Stroke = o.v
}

// StrokeDasharrayOpt applies to G
func (o StrokeDasharrayOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.StrokeDasharray = o.v
}

// StrokeDashoffsetOpt applies to G
func (o StrokeDashoffsetOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.StrokeDashoffset = o.v
}

// StrokeLinecapOpt applies to G
func (o StrokeLinecapOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.StrokeLinecap = o.v
}

// StrokeLinejoinOpt applies to G
func (o StrokeLinejoinOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.StrokeLinejoin = o.v
}

// StrokeMiterlimitOpt applies to G
func (o StrokeMiterlimitOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.StrokeMiterlimit = o.v
}

// StrokeOpacityOpt applies to G
func (o StrokeOpacityOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.StrokeOpacity = o.v
}

// StrokeWidthOpt applies to G
func (o StrokeWidthOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.StrokeWidth = o.v
}

// SystemLanguageOpt applies to G
func (o SystemLanguageOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.SystemLanguage = o.v
}

// TextAnchorOpt applies to G
func (o TextAnchorOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.TextAnchor = o.v
}

// TextDecorationOpt applies to G
func (o TextDecorationOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.TextDecoration = o.v
}

// TextRenderingOpt applies to G
func (o TextRenderingOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.TextRendering = o.v
}

// TransformOpt applies to G
func (o TransformOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.Transform = o.v
}

// UnicodeBidiOpt applies to G
func (o UnicodeBidiOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.UnicodeBidi = o.v
}

// VisibilityOpt applies to G
func (o VisibilityOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.Visibility = o.v
}

// WordSpacingOpt applies to G
func (o WordSpacingOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.WordSpacing = o.v
}

// WritingModeOpt applies to G
func (o WritingModeOpt) applyG(a *GAttrs, _ *[]html.Component) {
	a.WritingMode = o.v
}

// writeAttrs writes the SVG attributes to the string builder
func (a *GAttrs) writeAttrs(sb *strings.Builder) {
	WriteSvgGlobal(sb, &a.SvgGlobal)
	if a.AlignmentBaseline != "" {
		SvgAttr(sb, "alignment-baseline", a.AlignmentBaseline)
	}
	if a.BaselineShift != "" {
		SvgAttr(sb, "baseline-shift", a.BaselineShift)
	}
	if a.Clip != "" {
		SvgAttr(sb, "clip", a.Clip)
	}
	if a.ClipPath != "" {
		SvgAttr(sb, "clip-path", a.ClipPath)
	}
	if a.ClipRule != "" {
		SvgAttr(sb, "clip-rule", a.ClipRule)
	}
	if a.Color != "" {
		SvgAttr(sb, "color", a.Color)
	}
	if a.ColorInterpolation != "" {
		SvgAttr(sb, "color-interpolation", a.ColorInterpolation)
	}
	if a.ColorInterpolationFilters != "" {
		SvgAttr(sb, "color-interpolation-filters", a.ColorInterpolationFilters)
	}
	if a.ColorProfile != "" {
		SvgAttr(sb, "color-profile", a.ColorProfile)
	}
	if a.ColorRendering != "" {
		SvgAttr(sb, "color-rendering", a.ColorRendering)
	}
	if a.Cursor != "" {
		SvgAttr(sb, "cursor", a.Cursor)
	}
	if a.Direction != "" {
		SvgAttr(sb, "direction", a.Direction)
	}
	if a.Display != "" {
		SvgAttr(sb, "display", a.Display)
	}
	if a.DominantBaseline != "" {
		SvgAttr(sb, "dominant-baseline", a.DominantBaseline)
	}
	if a.EnableBackground != "" {
		SvgAttr(sb, "enable-background", a.EnableBackground)
	}
	if a.ExternalResourcesRequired != "" {
		SvgAttr(sb, "externalResourcesRequired", a.ExternalResourcesRequired)
	}
	if a.Fill != "" {
		SvgAttr(sb, "fill", a.Fill)
	}
	if a.FillOpacity != "" {
		SvgAttr(sb, "fill-opacity", a.FillOpacity)
	}
	if a.FillRule != "" {
		SvgAttr(sb, "fill-rule", a.FillRule)
	}
	if a.Filter != "" {
		SvgAttr(sb, "filter", a.Filter)
	}
	if a.FloodColor != "" {
		SvgAttr(sb, "flood-color", a.FloodColor)
	}
	if a.FloodOpacity != "" {
		SvgAttr(sb, "flood-opacity", a.FloodOpacity)
	}
	if a.FocusHighlight != "" {
		SvgAttr(sb, "focusHighlight", a.FocusHighlight)
	}
	if a.Focusable {
		SvgBoolAttr(sb, "focusable")
	}
	if a.FontFamily != "" {
		SvgAttr(sb, "font-family", a.FontFamily)
	}
	if a.FontSize != "" {
		SvgAttr(sb, "font-size", a.FontSize)
	}
	if a.FontSizeAdjust != "" {
		SvgAttr(sb, "font-size-adjust", a.FontSizeAdjust)
	}
	if a.FontStretch != "" {
		SvgAttr(sb, "font-stretch", a.FontStretch)
	}
	if a.FontStyle != "" {
		SvgAttr(sb, "font-style", a.FontStyle)
	}
	if a.FontVariant != "" {
		SvgAttr(sb, "font-variant", a.FontVariant)
	}
	if a.FontWeight != "" {
		SvgAttr(sb, "font-weight", a.FontWeight)
	}
	if a.GlyphOrientationHorizontal != "" {
		SvgAttr(sb, "glyph-orientation-horizontal", a.GlyphOrientationHorizontal)
	}
	if a.GlyphOrientationVertical != "" {
		SvgAttr(sb, "glyph-orientation-vertical", a.GlyphOrientationVertical)
	}
	if a.ImageRendering != "" {
		SvgAttr(sb, "image-rendering", a.ImageRendering)
	}
	if a.Kerning != "" {
		SvgAttr(sb, "kerning", a.Kerning)
	}
	if a.LetterSpacing != "" {
		SvgAttr(sb, "letter-spacing", a.LetterSpacing)
	}
	if a.LightingColor != "" {
		SvgAttr(sb, "lighting-color", a.LightingColor)
	}
	if a.MarkerEnd != "" {
		SvgAttr(sb, "marker-end", a.MarkerEnd)
	}
	if a.MarkerMid != "" {
		SvgAttr(sb, "marker-mid", a.MarkerMid)
	}
	if a.MarkerStart != "" {
		SvgAttr(sb, "marker-start", a.MarkerStart)
	}
	if a.Mask != "" {
		SvgAttr(sb, "mask", a.Mask)
	}
	if a.NavDown != "" {
		SvgAttr(sb, "nav-down", a.NavDown)
	}
	if a.NavDownLeft != "" {
		SvgAttr(sb, "nav-down-left", a.NavDownLeft)
	}
	if a.NavDownRight != "" {
		SvgAttr(sb, "nav-down-right", a.NavDownRight)
	}
	if a.NavLeft != "" {
		SvgAttr(sb, "nav-left", a.NavLeft)
	}
	if a.NavNext != "" {
		SvgAttr(sb, "nav-next", a.NavNext)
	}
	if a.NavPrev != "" {
		SvgAttr(sb, "nav-prev", a.NavPrev)
	}
	if a.NavRight != "" {
		SvgAttr(sb, "nav-right", a.NavRight)
	}
	if a.NavUp != "" {
		SvgAttr(sb, "nav-up", a.NavUp)
	}
	if a.NavUpLeft != "" {
		SvgAttr(sb, "nav-up-left", a.NavUpLeft)
	}
	if a.NavUpRight != "" {
		SvgAttr(sb, "nav-up-right", a.NavUpRight)
	}
	if a.Opacity != "" {
		SvgAttr(sb, "opacity", a.Opacity)
	}
	if a.Overflow != "" {
		SvgAttr(sb, "overflow", a.Overflow)
	}
	if a.PointerEvents != "" {
		SvgAttr(sb, "pointer-events", a.PointerEvents)
	}
	if a.RequiredExtensions != "" {
		SvgAttr(sb, "requiredExtensions", a.RequiredExtensions)
	}
	if a.RequiredFeatures != "" {
		SvgAttr(sb, "requiredFeatures", a.RequiredFeatures)
	}
	if a.RequiredFonts != "" {
		SvgAttr(sb, "requiredFonts", a.RequiredFonts)
	}
	if a.RequiredFormats != "" {
		SvgAttr(sb, "requiredFormats", a.RequiredFormats)
	}
	if a.ShapeRendering != "" {
		SvgAttr(sb, "shape-rendering", a.ShapeRendering)
	}
	if a.StopColor != "" {
		SvgAttr(sb, "stop-color", a.StopColor)
	}
	if a.StopOpacity != "" {
		SvgAttr(sb, "stop-opacity", a.StopOpacity)
	}
	if a.Stroke != "" {
		SvgAttr(sb, "stroke", a.Stroke)
	}
	if a.StrokeDasharray != "" {
		SvgAttr(sb, "stroke-dasharray", a.StrokeDasharray)
	}
	if a.StrokeDashoffset != "" {
		SvgAttr(sb, "stroke-dashoffset", a.StrokeDashoffset)
	}
	if a.StrokeLinecap != "" {
		SvgAttr(sb, "stroke-linecap", a.StrokeLinecap)
	}
	if a.StrokeLinejoin != "" {
		SvgAttr(sb, "stroke-linejoin", a.StrokeLinejoin)
	}
	if a.StrokeMiterlimit != "" {
		SvgAttr(sb, "stroke-miterlimit", a.StrokeMiterlimit)
	}
	if a.StrokeOpacity != "" {
		SvgAttr(sb, "stroke-opacity", a.StrokeOpacity)
	}
	if a.StrokeWidth != "" {
		SvgAttr(sb, "stroke-width", a.StrokeWidth)
	}
	if a.SystemLanguage != "" {
		SvgAttr(sb, "systemLanguage", a.SystemLanguage)
	}
	if a.TextAnchor != "" {
		SvgAttr(sb, "text-anchor", a.TextAnchor)
	}
	if a.TextDecoration != "" {
		SvgAttr(sb, "text-decoration", a.TextDecoration)
	}
	if a.TextRendering != "" {
		SvgAttr(sb, "text-rendering", a.TextRendering)
	}
	if a.Transform != "" {
		SvgAttr(sb, "transform", a.Transform)
	}
	if a.UnicodeBidi != "" {
		SvgAttr(sb, "unicode-bidi", a.UnicodeBidi)
	}
	if a.Visibility != "" {
		SvgAttr(sb, "visibility", a.Visibility)
	}
	if a.WordSpacing != "" {
		SvgAttr(sb, "word-spacing", a.WordSpacing)
	}
	if a.WritingMode != "" {
		SvgAttr(sb, "writing-mode", a.WritingMode)
	}
}
