// Code generated by gen-svg; DO NOT EDIT.
package svg

import (
	"strings"

	"github.com/plainkit/html"
)

type ColorProfileAttrs struct {
	html.GlobalAttrs
	Local           string
	Name            string
	RenderingIntent string
}

func ColorProfile(attrs ColorProfileAttrs, children ...html.Component) html.Node {
	return html.Node{Tag: "color-profile", Attrs: &attrs, Kids: children}
}

func (a *ColorProfileAttrs) writeAttrs(sb *strings.Builder) {
	html.WriteGlobal(sb, &a.GlobalAttrs)
	if a.Local != "" {
		html.Attr(sb, "local", a.Local)
	}
	if a.Name != "" {
		html.Attr(sb, "name", a.Name)
	}
	if a.RenderingIntent != "" {
		html.Attr(sb, "rendering-intent", a.RenderingIntent)
	}
}
