// Code generated by gen-svg; DO NOT EDIT.

package svg

import (
	"strings"

	"github.com/plainkit/html"
)

// MetadataAttrs holds the attributes for the metadata SVG element
type MetadataAttrs struct {
	SvgGlobal          SvgGlobalAttrs
	RequiredExtensions string
	RequiredFeatures   string
	RequiredFonts      string
	RequiredFormats    string
	SystemLanguage     string
}

// MetadataArg interface for metadata element arguments
type MetadataArg interface {
	applyMetadata(*MetadataAttrs, *[]html.Component)
}

// defaultMetadataAttrs creates default attributes for metadata
func defaultMetadataAttrs() *MetadataAttrs {
	return &MetadataAttrs{
		SvgGlobal: SvgGlobalAttrs{},
	}
}

// Metadata creates an SVG metadata element
func Metadata(args ...MetadataArg) html.Node {
	a := defaultMetadataAttrs()
	var kids []html.Component
	for _, ar := range args {
		ar.applyMetadata(a, &kids)
	}
	return html.Node{
		Tag:   "metadata",
		Attrs: a,
		Kids:  kids,
	}
}

// Global applies global SVG attributes to metadata
func (g Global) applyMetadata(a *MetadataAttrs, _ *[]html.Component) {
	g.do(&a.SvgGlobal)
}

// RequiredExtensionsOpt applies to Metadata
func (o RequiredExtensionsOpt) applyMetadata(a *MetadataAttrs, _ *[]html.Component) {
	a.RequiredExtensions = o.v
}

// RequiredFeaturesOpt applies to Metadata
func (o RequiredFeaturesOpt) applyMetadata(a *MetadataAttrs, _ *[]html.Component) {
	a.RequiredFeatures = o.v
}

// RequiredFontsOpt applies to Metadata
func (o RequiredFontsOpt) applyMetadata(a *MetadataAttrs, _ *[]html.Component) {
	a.RequiredFonts = o.v
}

// RequiredFormatsOpt applies to Metadata
func (o RequiredFormatsOpt) applyMetadata(a *MetadataAttrs, _ *[]html.Component) {
	a.RequiredFormats = o.v
}

// SystemLanguageOpt applies to Metadata
func (o SystemLanguageOpt) applyMetadata(a *MetadataAttrs, _ *[]html.Component) {
	a.SystemLanguage = o.v
}

// writeAttrs writes the SVG attributes to the string builder
func (a *MetadataAttrs) writeAttrs(sb *strings.Builder) {
	WriteSvgGlobal(sb, &a.SvgGlobal)
	if a.RequiredExtensions != "" {
		SvgAttr(sb, "requiredExtensions", a.RequiredExtensions)
	}
	if a.RequiredFeatures != "" {
		SvgAttr(sb, "requiredFeatures", a.RequiredFeatures)
	}
	if a.RequiredFonts != "" {
		SvgAttr(sb, "requiredFonts", a.RequiredFonts)
	}
	if a.RequiredFormats != "" {
		SvgAttr(sb, "requiredFormats", a.RequiredFormats)
	}
	if a.SystemLanguage != "" {
		SvgAttr(sb, "systemLanguage", a.SystemLanguage)
	}
}
