// Code generated by gen-svg; DO NOT EDIT.
package svg

import (
	"strings"

	"github.com/plainkit/html"
)

// StyleAttrs holds the attributes for the style SVG element
type StyleAttrs struct {
	html.GlobalAttrs
	Media string
	Title string
	Type  string
}

// Style creates an SVG style element
func Style(attrs StyleAttrs, children ...html.Component) html.Node {
	return html.Node{
		Tag:   "style",
		Attrs: &attrs,
		Kids:  children,
	}
}

// writeAttrs writes the HTML attributes to the string builder
func (a *StyleAttrs) writeAttrs(sb *strings.Builder) {
	html.WriteGlobal(sb, &a.GlobalAttrs)
	if a.Media != "" {
		html.Attr(sb, "media", a.Media)
	}
	if a.Title != "" {
		html.Attr(sb, "title", a.Title)
	}
	if a.Type != "" {
		html.Attr(sb, "type", a.Type)
	}
}
