// Code generated by gen-svg; DO NOT EDIT.
package svg

import (
	"strings"

	"github.com/plainkit/html"
)

type TbreakAttrs struct {
	html.GlobalAttrs
	RequiredExtensions string
	RequiredFeatures   string
	RequiredFonts      string
	RequiredFormats    string
	SystemLanguage     string
}

func Tbreak(attrs TbreakAttrs, children ...html.Component) html.Node {
	return html.Node{Tag: "tbreak", Attrs: &attrs, Kids: children}
}

func (a *TbreakAttrs) writeAttrs(sb *strings.Builder) {
	html.WriteGlobal(sb, &a.GlobalAttrs)
	if a.RequiredExtensions != "" {
		html.Attr(sb, "requiredExtensions", a.RequiredExtensions)
	}
	if a.RequiredFeatures != "" {
		html.Attr(sb, "requiredFeatures", a.RequiredFeatures)
	}
	if a.RequiredFonts != "" {
		html.Attr(sb, "requiredFonts", a.RequiredFonts)
	}
	if a.RequiredFormats != "" {
		html.Attr(sb, "requiredFormats", a.RequiredFormats)
	}
	if a.SystemLanguage != "" {
		html.Attr(sb, "systemLanguage", a.SystemLanguage)
	}
}
