// Code generated by gen-svg; DO NOT EDIT.

package svg

import (
	"strings"

	"github.com/plainkit/html"
)

// ImageAttrs holds the attributes for the image SVG element
type ImageAttrs struct {
	SvgGlobal                  SvgGlobalAttrs
	AlignmentBaseline          string
	BaselineShift              string
	Clip                       string
	ClipPath                   string
	ClipRule                   string
	Color                      string
	ColorInterpolation         string
	ColorInterpolationFilters  string
	ColorProfile               string
	ColorRendering             string
	Crossorigin                bool
	Cursor                     string
	Direction                  string
	Display                    string
	DominantBaseline           string
	EnableBackground           string
	ExternalResourcesRequired  string
	Fill                       string
	FillOpacity                string
	FillRule                   string
	Filter                     string
	FloodColor                 string
	FloodOpacity               string
	FocusHighlight             string
	Focusable                  bool
	FontFamily                 string
	FontSize                   string
	FontSizeAdjust             string
	FontStretch                string
	FontStyle                  string
	FontVariant                string
	FontWeight                 string
	GlyphOrientationHorizontal string
	GlyphOrientationVertical   string
	Height                     string
	Href                       string
	ImageRendering             string
	Kerning                    string
	LetterSpacing              string
	LightingColor              string
	MarkerEnd                  string
	MarkerMid                  string
	MarkerStart                string
	Mask                       string
	NavDown                    string
	NavDownLeft                string
	NavDownRight               string
	NavLeft                    string
	NavNext                    string
	NavPrev                    string
	NavRight                   string
	NavUp                      string
	NavUpLeft                  string
	NavUpRight                 string
	Opacity                    string
	Overflow                   string
	PointerEvents              string
	PreserveAspectRatio        string
	RequiredExtensions         string
	RequiredFeatures           string
	RequiredFonts              string
	RequiredFormats            string
	ShapeRendering             string
	StopColor                  string
	StopOpacity                string
	Stroke                     string
	StrokeDasharray            string
	StrokeDashoffset           string
	StrokeLinecap              string
	StrokeLinejoin             string
	StrokeMiterlimit           string
	StrokeOpacity              string
	StrokeWidth                string
	SystemLanguage             string
	TextAnchor                 string
	TextDecoration             string
	TextRendering              string
	Transform                  string
	Type                       string
	UnicodeBidi                string
	Visibility                 string
	Width                      string
	WordSpacing                string
	WritingMode                string
	X                          string
	Y                          string
}

// ImageArg interface for image element arguments
type ImageArg interface {
	applyImage(*ImageAttrs, *[]html.Component)
}

// defaultImageAttrs creates default attributes for image
func defaultImageAttrs() *ImageAttrs {
	return &ImageAttrs{
		SvgGlobal: SvgGlobalAttrs{},
	}
}

// Image creates an SVG image element
func Image(args ...ImageArg) html.Node {
	a := defaultImageAttrs()
	var kids []html.Component
	for _, ar := range args {
		ar.applyImage(a, &kids)
	}
	return html.Node{
		Tag:   "image",
		Attrs: a,
		Kids:  kids,
	}
}

// Global applies global SVG attributes to image
func (g Global) applyImage(a *ImageAttrs, _ *[]html.Component) {
	g.do(&a.SvgGlobal)
}

// AlignmentBaselineOpt applies to Image
func (o AlignmentBaselineOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.AlignmentBaseline = o.v
}

// BaselineShiftOpt applies to Image
func (o BaselineShiftOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.BaselineShift = o.v
}

// ClipOpt applies to Image
func (o ClipOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.Clip = o.v
}

// ClipPathOpt applies to Image
func (o ClipPathOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.ClipPath = o.v
}

// ClipRuleOpt applies to Image
func (o ClipRuleOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.ClipRule = o.v
}

// ColorOpt applies to Image
func (o ColorOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.Color = o.v
}

// ColorInterpolationOpt applies to Image
func (o ColorInterpolationOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.ColorInterpolation = o.v
}

// ColorInterpolationFiltersOpt applies to Image
func (o ColorInterpolationFiltersOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.ColorInterpolationFilters = o.v
}

// ColorProfileOpt applies to Image
func (o ColorProfileOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.ColorProfile = o.v
}

// ColorRenderingOpt applies to Image
func (o ColorRenderingOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.ColorRendering = o.v
}

// CrossoriginOpt applies to Image
func (o CrossoriginOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.Crossorigin = true
}

// CursorOpt applies to Image
func (o CursorOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.Cursor = o.v
}

// DirectionOpt applies to Image
func (o DirectionOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.Direction = o.v
}

// DisplayOpt applies to Image
func (o DisplayOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.Display = o.v
}

// DominantBaselineOpt applies to Image
func (o DominantBaselineOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.DominantBaseline = o.v
}

// EnableBackgroundOpt applies to Image
func (o EnableBackgroundOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.EnableBackground = o.v
}

// ExternalResourcesRequiredOpt applies to Image
func (o ExternalResourcesRequiredOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.ExternalResourcesRequired = o.v
}

// FillOpt applies to Image
func (o FillOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.Fill = o.v
}

// FillOpacityOpt applies to Image
func (o FillOpacityOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.FillOpacity = o.v
}

// FillRuleOpt applies to Image
func (o FillRuleOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.FillRule = o.v
}

// FilterOpt applies to Image
func (o FilterOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.Filter = o.v
}

// FloodColorOpt applies to Image
func (o FloodColorOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.FloodColor = o.v
}

// FloodOpacityOpt applies to Image
func (o FloodOpacityOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.FloodOpacity = o.v
}

// FocusHighlightOpt applies to Image
func (o FocusHighlightOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.FocusHighlight = o.v
}

// FocusableOpt applies to Image
func (o FocusableOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.Focusable = true
}

// FontFamilyOpt applies to Image
func (o FontFamilyOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.FontFamily = o.v
}

// FontSizeOpt applies to Image
func (o FontSizeOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.FontSize = o.v
}

// FontSizeAdjustOpt applies to Image
func (o FontSizeAdjustOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.FontSizeAdjust = o.v
}

// FontStretchOpt applies to Image
func (o FontStretchOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.FontStretch = o.v
}

// FontStyleOpt applies to Image
func (o FontStyleOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.FontStyle = o.v
}

// FontVariantOpt applies to Image
func (o FontVariantOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.FontVariant = o.v
}

// FontWeightOpt applies to Image
func (o FontWeightOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.FontWeight = o.v
}

// GlyphOrientationHorizontalOpt applies to Image
func (o GlyphOrientationHorizontalOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.GlyphOrientationHorizontal = o.v
}

// GlyphOrientationVerticalOpt applies to Image
func (o GlyphOrientationVerticalOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.GlyphOrientationVertical = o.v
}

// HeightOpt applies to Image
func (o HeightOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.Height = o.v
}

// HrefOpt applies to Image
func (o HrefOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.Href = o.v
}

// ImageRenderingOpt applies to Image
func (o ImageRenderingOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.ImageRendering = o.v
}

// KerningOpt applies to Image
func (o KerningOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.Kerning = o.v
}

// LetterSpacingOpt applies to Image
func (o LetterSpacingOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.LetterSpacing = o.v
}

// LightingColorOpt applies to Image
func (o LightingColorOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.LightingColor = o.v
}

// MarkerEndOpt applies to Image
func (o MarkerEndOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.MarkerEnd = o.v
}

// MarkerMidOpt applies to Image
func (o MarkerMidOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.MarkerMid = o.v
}

// MarkerStartOpt applies to Image
func (o MarkerStartOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.MarkerStart = o.v
}

// MaskOpt applies to Image
func (o MaskOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.Mask = o.v
}

// NavDownOpt applies to Image
func (o NavDownOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.NavDown = o.v
}

// NavDownLeftOpt applies to Image
func (o NavDownLeftOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.NavDownLeft = o.v
}

// NavDownRightOpt applies to Image
func (o NavDownRightOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.NavDownRight = o.v
}

// NavLeftOpt applies to Image
func (o NavLeftOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.NavLeft = o.v
}

// NavNextOpt applies to Image
func (o NavNextOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.NavNext = o.v
}

// NavPrevOpt applies to Image
func (o NavPrevOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.NavPrev = o.v
}

// NavRightOpt applies to Image
func (o NavRightOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.NavRight = o.v
}

// NavUpOpt applies to Image
func (o NavUpOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.NavUp = o.v
}

// NavUpLeftOpt applies to Image
func (o NavUpLeftOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.NavUpLeft = o.v
}

// NavUpRightOpt applies to Image
func (o NavUpRightOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.NavUpRight = o.v
}

// OpacityOpt applies to Image
func (o OpacityOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.Opacity = o.v
}

// OverflowOpt applies to Image
func (o OverflowOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.Overflow = o.v
}

// PointerEventsOpt applies to Image
func (o PointerEventsOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.PointerEvents = o.v
}

// PreserveAspectRatioOpt applies to Image
func (o PreserveAspectRatioOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.PreserveAspectRatio = o.v
}

// RequiredExtensionsOpt applies to Image
func (o RequiredExtensionsOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.RequiredExtensions = o.v
}

// RequiredFeaturesOpt applies to Image
func (o RequiredFeaturesOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.RequiredFeatures = o.v
}

// RequiredFontsOpt applies to Image
func (o RequiredFontsOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.RequiredFonts = o.v
}

// RequiredFormatsOpt applies to Image
func (o RequiredFormatsOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.RequiredFormats = o.v
}

// ShapeRenderingOpt applies to Image
func (o ShapeRenderingOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.ShapeRendering = o.v
}

// StopColorOpt applies to Image
func (o StopColorOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.StopColor = o.v
}

// StopOpacityOpt applies to Image
func (o StopOpacityOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.StopOpacity = o.v
}

// StrokeOpt applies to Image
func (o StrokeOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.Stroke = o.v
}

// StrokeDasharrayOpt applies to Image
func (o StrokeDasharrayOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.StrokeDasharray = o.v
}

// StrokeDashoffsetOpt applies to Image
func (o StrokeDashoffsetOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.StrokeDashoffset = o.v
}

// StrokeLinecapOpt applies to Image
func (o StrokeLinecapOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.StrokeLinecap = o.v
}

// StrokeLinejoinOpt applies to Image
func (o StrokeLinejoinOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.StrokeLinejoin = o.v
}

// StrokeMiterlimitOpt applies to Image
func (o StrokeMiterlimitOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.StrokeMiterlimit = o.v
}

// StrokeOpacityOpt applies to Image
func (o StrokeOpacityOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.StrokeOpacity = o.v
}

// StrokeWidthOpt applies to Image
func (o StrokeWidthOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.StrokeWidth = o.v
}

// SystemLanguageOpt applies to Image
func (o SystemLanguageOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.SystemLanguage = o.v
}

// TextAnchorOpt applies to Image
func (o TextAnchorOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.TextAnchor = o.v
}

// TextDecorationOpt applies to Image
func (o TextDecorationOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.TextDecoration = o.v
}

// TextRenderingOpt applies to Image
func (o TextRenderingOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.TextRendering = o.v
}

// TransformOpt applies to Image
func (o TransformOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.Transform = o.v
}

// TypeOpt applies to Image
func (o TypeOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.Type = o.v
}

// UnicodeBidiOpt applies to Image
func (o UnicodeBidiOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.UnicodeBidi = o.v
}

// VisibilityOpt applies to Image
func (o VisibilityOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.Visibility = o.v
}

// WidthOpt applies to Image
func (o WidthOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.Width = o.v
}

// WordSpacingOpt applies to Image
func (o WordSpacingOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.WordSpacing = o.v
}

// WritingModeOpt applies to Image
func (o WritingModeOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.WritingMode = o.v
}

// XOpt applies to Image
func (o XOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.X = o.v
}

// YOpt applies to Image
func (o YOpt) applyImage(a *ImageAttrs, _ *[]html.Component) {
	a.Y = o.v
}

// writeAttrs writes the SVG attributes to the string builder
func (a *ImageAttrs) writeAttrs(sb *strings.Builder) {
	WriteSvgGlobal(sb, &a.SvgGlobal)
	if a.AlignmentBaseline != "" {
		SvgAttr(sb, "alignment-baseline", a.AlignmentBaseline)
	}
	if a.BaselineShift != "" {
		SvgAttr(sb, "baseline-shift", a.BaselineShift)
	}
	if a.Clip != "" {
		SvgAttr(sb, "clip", a.Clip)
	}
	if a.ClipPath != "" {
		SvgAttr(sb, "clip-path", a.ClipPath)
	}
	if a.ClipRule != "" {
		SvgAttr(sb, "clip-rule", a.ClipRule)
	}
	if a.Color != "" {
		SvgAttr(sb, "color", a.Color)
	}
	if a.ColorInterpolation != "" {
		SvgAttr(sb, "color-interpolation", a.ColorInterpolation)
	}
	if a.ColorInterpolationFilters != "" {
		SvgAttr(sb, "color-interpolation-filters", a.ColorInterpolationFilters)
	}
	if a.ColorProfile != "" {
		SvgAttr(sb, "color-profile", a.ColorProfile)
	}
	if a.ColorRendering != "" {
		SvgAttr(sb, "color-rendering", a.ColorRendering)
	}
	if a.Crossorigin {
		SvgBoolAttr(sb, "crossorigin")
	}
	if a.Cursor != "" {
		SvgAttr(sb, "cursor", a.Cursor)
	}
	if a.Direction != "" {
		SvgAttr(sb, "direction", a.Direction)
	}
	if a.Display != "" {
		SvgAttr(sb, "display", a.Display)
	}
	if a.DominantBaseline != "" {
		SvgAttr(sb, "dominant-baseline", a.DominantBaseline)
	}
	if a.EnableBackground != "" {
		SvgAttr(sb, "enable-background", a.EnableBackground)
	}
	if a.ExternalResourcesRequired != "" {
		SvgAttr(sb, "externalResourcesRequired", a.ExternalResourcesRequired)
	}
	if a.Fill != "" {
		SvgAttr(sb, "fill", a.Fill)
	}
	if a.FillOpacity != "" {
		SvgAttr(sb, "fill-opacity", a.FillOpacity)
	}
	if a.FillRule != "" {
		SvgAttr(sb, "fill-rule", a.FillRule)
	}
	if a.Filter != "" {
		SvgAttr(sb, "filter", a.Filter)
	}
	if a.FloodColor != "" {
		SvgAttr(sb, "flood-color", a.FloodColor)
	}
	if a.FloodOpacity != "" {
		SvgAttr(sb, "flood-opacity", a.FloodOpacity)
	}
	if a.FocusHighlight != "" {
		SvgAttr(sb, "focusHighlight", a.FocusHighlight)
	}
	if a.Focusable {
		SvgBoolAttr(sb, "focusable")
	}
	if a.FontFamily != "" {
		SvgAttr(sb, "font-family", a.FontFamily)
	}
	if a.FontSize != "" {
		SvgAttr(sb, "font-size", a.FontSize)
	}
	if a.FontSizeAdjust != "" {
		SvgAttr(sb, "font-size-adjust", a.FontSizeAdjust)
	}
	if a.FontStretch != "" {
		SvgAttr(sb, "font-stretch", a.FontStretch)
	}
	if a.FontStyle != "" {
		SvgAttr(sb, "font-style", a.FontStyle)
	}
	if a.FontVariant != "" {
		SvgAttr(sb, "font-variant", a.FontVariant)
	}
	if a.FontWeight != "" {
		SvgAttr(sb, "font-weight", a.FontWeight)
	}
	if a.GlyphOrientationHorizontal != "" {
		SvgAttr(sb, "glyph-orientation-horizontal", a.GlyphOrientationHorizontal)
	}
	if a.GlyphOrientationVertical != "" {
		SvgAttr(sb, "glyph-orientation-vertical", a.GlyphOrientationVertical)
	}
	if a.Height != "" {
		SvgAttr(sb, "height", a.Height)
	}
	if a.Href != "" {
		SvgAttr(sb, "href", a.Href)
	}
	if a.ImageRendering != "" {
		SvgAttr(sb, "image-rendering", a.ImageRendering)
	}
	if a.Kerning != "" {
		SvgAttr(sb, "kerning", a.Kerning)
	}
	if a.LetterSpacing != "" {
		SvgAttr(sb, "letter-spacing", a.LetterSpacing)
	}
	if a.LightingColor != "" {
		SvgAttr(sb, "lighting-color", a.LightingColor)
	}
	if a.MarkerEnd != "" {
		SvgAttr(sb, "marker-end", a.MarkerEnd)
	}
	if a.MarkerMid != "" {
		SvgAttr(sb, "marker-mid", a.MarkerMid)
	}
	if a.MarkerStart != "" {
		SvgAttr(sb, "marker-start", a.MarkerStart)
	}
	if a.Mask != "" {
		SvgAttr(sb, "mask", a.Mask)
	}
	if a.NavDown != "" {
		SvgAttr(sb, "nav-down", a.NavDown)
	}
	if a.NavDownLeft != "" {
		SvgAttr(sb, "nav-down-left", a.NavDownLeft)
	}
	if a.NavDownRight != "" {
		SvgAttr(sb, "nav-down-right", a.NavDownRight)
	}
	if a.NavLeft != "" {
		SvgAttr(sb, "nav-left", a.NavLeft)
	}
	if a.NavNext != "" {
		SvgAttr(sb, "nav-next", a.NavNext)
	}
	if a.NavPrev != "" {
		SvgAttr(sb, "nav-prev", a.NavPrev)
	}
	if a.NavRight != "" {
		SvgAttr(sb, "nav-right", a.NavRight)
	}
	if a.NavUp != "" {
		SvgAttr(sb, "nav-up", a.NavUp)
	}
	if a.NavUpLeft != "" {
		SvgAttr(sb, "nav-up-left", a.NavUpLeft)
	}
	if a.NavUpRight != "" {
		SvgAttr(sb, "nav-up-right", a.NavUpRight)
	}
	if a.Opacity != "" {
		SvgAttr(sb, "opacity", a.Opacity)
	}
	if a.Overflow != "" {
		SvgAttr(sb, "overflow", a.Overflow)
	}
	if a.PointerEvents != "" {
		SvgAttr(sb, "pointer-events", a.PointerEvents)
	}
	if a.PreserveAspectRatio != "" {
		SvgAttr(sb, "preserveAspectRatio", a.PreserveAspectRatio)
	}
	if a.RequiredExtensions != "" {
		SvgAttr(sb, "requiredExtensions", a.RequiredExtensions)
	}
	if a.RequiredFeatures != "" {
		SvgAttr(sb, "requiredFeatures", a.RequiredFeatures)
	}
	if a.RequiredFonts != "" {
		SvgAttr(sb, "requiredFonts", a.RequiredFonts)
	}
	if a.RequiredFormats != "" {
		SvgAttr(sb, "requiredFormats", a.RequiredFormats)
	}
	if a.ShapeRendering != "" {
		SvgAttr(sb, "shape-rendering", a.ShapeRendering)
	}
	if a.StopColor != "" {
		SvgAttr(sb, "stop-color", a.StopColor)
	}
	if a.StopOpacity != "" {
		SvgAttr(sb, "stop-opacity", a.StopOpacity)
	}
	if a.Stroke != "" {
		SvgAttr(sb, "stroke", a.Stroke)
	}
	if a.StrokeDasharray != "" {
		SvgAttr(sb, "stroke-dasharray", a.StrokeDasharray)
	}
	if a.StrokeDashoffset != "" {
		SvgAttr(sb, "stroke-dashoffset", a.StrokeDashoffset)
	}
	if a.StrokeLinecap != "" {
		SvgAttr(sb, "stroke-linecap", a.StrokeLinecap)
	}
	if a.StrokeLinejoin != "" {
		SvgAttr(sb, "stroke-linejoin", a.StrokeLinejoin)
	}
	if a.StrokeMiterlimit != "" {
		SvgAttr(sb, "stroke-miterlimit", a.StrokeMiterlimit)
	}
	if a.StrokeOpacity != "" {
		SvgAttr(sb, "stroke-opacity", a.StrokeOpacity)
	}
	if a.StrokeWidth != "" {
		SvgAttr(sb, "stroke-width", a.StrokeWidth)
	}
	if a.SystemLanguage != "" {
		SvgAttr(sb, "systemLanguage", a.SystemLanguage)
	}
	if a.TextAnchor != "" {
		SvgAttr(sb, "text-anchor", a.TextAnchor)
	}
	if a.TextDecoration != "" {
		SvgAttr(sb, "text-decoration", a.TextDecoration)
	}
	if a.TextRendering != "" {
		SvgAttr(sb, "text-rendering", a.TextRendering)
	}
	if a.Transform != "" {
		SvgAttr(sb, "transform", a.Transform)
	}
	if a.Type != "" {
		SvgAttr(sb, "type", a.Type)
	}
	if a.UnicodeBidi != "" {
		SvgAttr(sb, "unicode-bidi", a.UnicodeBidi)
	}
	if a.Visibility != "" {
		SvgAttr(sb, "visibility", a.Visibility)
	}
	if a.Width != "" {
		SvgAttr(sb, "width", a.Width)
	}
	if a.WordSpacing != "" {
		SvgAttr(sb, "word-spacing", a.WordSpacing)
	}
	if a.WritingMode != "" {
		SvgAttr(sb, "writing-mode", a.WritingMode)
	}
	if a.X != "" {
		SvgAttr(sb, "x", a.X)
	}
	if a.Y != "" {
		SvgAttr(sb, "y", a.Y)
	}
}
