// Code generated by gen-svg; DO NOT EDIT.

package svg

import (
	"strings"

	"github.com/plainkit/html"
)

// FeSpotLightAttrs holds the attributes for the feSpotLight SVG element
type FeSpotLightAttrs struct {
	SvgGlobal         SvgGlobalAttrs
	LimitingConeAngle string
	PointsAtX         string
	PointsAtY         string
	PointsAtZ         string
	SpecularExponent  string
	X                 string
	Y                 string
	Z                 string
}

// FeSpotLightArg interface for feSpotLight element arguments
type FeSpotLightArg interface {
	applyFeSpotLight(*FeSpotLightAttrs, *[]html.Component)
}

// defaultFeSpotLightAttrs creates default attributes for feSpotLight
func defaultFeSpotLightAttrs() *FeSpotLightAttrs {
	return &FeSpotLightAttrs{
		SvgGlobal: SvgGlobalAttrs{},
	}
}

// FeSpotLight creates an SVG feSpotLight element
func FeSpotLight(args ...FeSpotLightArg) html.Node {
	a := defaultFeSpotLightAttrs()
	var kids []html.Component
	for _, ar := range args {
		ar.applyFeSpotLight(a, &kids)
	}
	return html.Node{
		Tag:   "feSpotLight",
		Attrs: a,
		Kids:  kids,
	}
}

// Global applies global SVG attributes to feSpotLight
func (g Global) applyFeSpotLight(a *FeSpotLightAttrs, _ *[]html.Component) {
	g.do(&a.SvgGlobal)
}

// LimitingConeAngleOpt applies to FeSpotLight
func (o LimitingConeAngleOpt) applyFeSpotLight(a *FeSpotLightAttrs, _ *[]html.Component) {
	a.LimitingConeAngle = o.v
}

// PointsAtXOpt applies to FeSpotLight
func (o PointsAtXOpt) applyFeSpotLight(a *FeSpotLightAttrs, _ *[]html.Component) {
	a.PointsAtX = o.v
}

// PointsAtYOpt applies to FeSpotLight
func (o PointsAtYOpt) applyFeSpotLight(a *FeSpotLightAttrs, _ *[]html.Component) {
	a.PointsAtY = o.v
}

// PointsAtZOpt applies to FeSpotLight
func (o PointsAtZOpt) applyFeSpotLight(a *FeSpotLightAttrs, _ *[]html.Component) {
	a.PointsAtZ = o.v
}

// SpecularExponentOpt applies to FeSpotLight
func (o SpecularExponentOpt) applyFeSpotLight(a *FeSpotLightAttrs, _ *[]html.Component) {
	a.SpecularExponent = o.v
}

// XOpt applies to FeSpotLight
func (o XOpt) applyFeSpotLight(a *FeSpotLightAttrs, _ *[]html.Component) {
	a.X = o.v
}

// YOpt applies to FeSpotLight
func (o YOpt) applyFeSpotLight(a *FeSpotLightAttrs, _ *[]html.Component) {
	a.Y = o.v
}

// ZOpt applies to FeSpotLight
func (o ZOpt) applyFeSpotLight(a *FeSpotLightAttrs, _ *[]html.Component) {
	a.Z = o.v
}

// writeAttrs writes the SVG attributes to the string builder
func (a *FeSpotLightAttrs) writeAttrs(sb *strings.Builder) {
	WriteSvgGlobal(sb, &a.SvgGlobal)
	if a.LimitingConeAngle != "" {
		SvgAttr(sb, "limitingConeAngle", a.LimitingConeAngle)
	}
	if a.PointsAtX != "" {
		SvgAttr(sb, "pointsAtX", a.PointsAtX)
	}
	if a.PointsAtY != "" {
		SvgAttr(sb, "pointsAtY", a.PointsAtY)
	}
	if a.PointsAtZ != "" {
		SvgAttr(sb, "pointsAtZ", a.PointsAtZ)
	}
	if a.SpecularExponent != "" {
		SvgAttr(sb, "specularExponent", a.SpecularExponent)
	}
	if a.X != "" {
		SvgAttr(sb, "x", a.X)
	}
	if a.Y != "" {
		SvgAttr(sb, "y", a.Y)
	}
	if a.Z != "" {
		SvgAttr(sb, "z", a.Z)
	}
}
