// Code generated by gen-svg; DO NOT EDIT.
package svg

import (
	"strings"

	"github.com/plainkit/html"
)

// TextPathAttrs holds the attributes for the textPath SVG element
type TextPathAttrs struct {
	html.GlobalAttrs
	AlignmentBaseline          string
	BaselineShift              string
	Clip                       string
	ClipPath                   string
	ClipRule                   string
	Color                      string
	ColorInterpolation         string
	ColorInterpolationFilters  string
	ColorProfile               string
	ColorRendering             string
	Cursor                     string
	Direction                  string
	Display                    string
	DominantBaseline           string
	EnableBackground           string
	ExternalResourcesRequired  string
	Fill                       string
	FillOpacity                string
	FillRule                   string
	Filter                     string
	FloodColor                 string
	FloodOpacity               string
	FontFamily                 string
	FontSize                   string
	FontSizeAdjust             string
	FontStretch                string
	FontStyle                  string
	FontVariant                string
	FontWeight                 string
	GlyphOrientationHorizontal string
	GlyphOrientationVertical   string
	Href                       string
	ImageRendering             string
	Kerning                    string
	LengthAdjust               string
	LetterSpacing              string
	LightingColor              string
	MarkerEnd                  string
	MarkerMid                  string
	MarkerStart                string
	Mask                       string
	Method                     string
	Opacity                    string
	Overflow                   string
	Path                       string
	PointerEvents              string
	RequiredExtensions         string
	RequiredFeatures           string
	ShapeRendering             string
	Side                       string
	Spacing                    string
	StartOffset                string
	StopColor                  string
	StopOpacity                string
	Stroke                     string
	StrokeDasharray            string
	StrokeDashoffset           string
	StrokeLinecap              string
	StrokeLinejoin             string
	StrokeMiterlimit           string
	StrokeOpacity              string
	StrokeWidth                string
	SystemLanguage             string
	TextAnchor                 string
	TextDecoration             string
	TextLength                 string
	TextRendering              string
	UnicodeBidi                string
	Visibility                 string
	WordSpacing                string
	WritingMode                string
}

// TextPath creates an SVG textPath element
func TextPath(attrs TextPathAttrs, children ...html.Component) html.Node {
	return html.Node{
		Tag:   "textPath",
		Attrs: &attrs,
		Kids:  children,
	}
}

// writeAttrs writes the HTML attributes to the string builder
func (a *TextPathAttrs) writeAttrs(sb *strings.Builder) {
	html.WriteGlobal(sb, &a.GlobalAttrs)
	if a.AlignmentBaseline != "" {
		html.Attr(sb, "alignment-baseline", a.AlignmentBaseline)
	}
	if a.BaselineShift != "" {
		html.Attr(sb, "baseline-shift", a.BaselineShift)
	}
	if a.Clip != "" {
		html.Attr(sb, "clip", a.Clip)
	}
	if a.ClipPath != "" {
		html.Attr(sb, "clip-path", a.ClipPath)
	}
	if a.ClipRule != "" {
		html.Attr(sb, "clip-rule", a.ClipRule)
	}
	if a.Color != "" {
		html.Attr(sb, "color", a.Color)
	}
	if a.ColorInterpolation != "" {
		html.Attr(sb, "color-interpolation", a.ColorInterpolation)
	}
	if a.ColorInterpolationFilters != "" {
		html.Attr(sb, "color-interpolation-filters", a.ColorInterpolationFilters)
	}
	if a.ColorProfile != "" {
		html.Attr(sb, "color-profile", a.ColorProfile)
	}
	if a.ColorRendering != "" {
		html.Attr(sb, "color-rendering", a.ColorRendering)
	}
	if a.Cursor != "" {
		html.Attr(sb, "cursor", a.Cursor)
	}
	if a.Direction != "" {
		html.Attr(sb, "direction", a.Direction)
	}
	if a.Display != "" {
		html.Attr(sb, "display", a.Display)
	}
	if a.DominantBaseline != "" {
		html.Attr(sb, "dominant-baseline", a.DominantBaseline)
	}
	if a.EnableBackground != "" {
		html.Attr(sb, "enable-background", a.EnableBackground)
	}
	if a.ExternalResourcesRequired != "" {
		html.Attr(sb, "externalResourcesRequired", a.ExternalResourcesRequired)
	}
	if a.Fill != "" {
		html.Attr(sb, "fill", a.Fill)
	}
	if a.FillOpacity != "" {
		html.Attr(sb, "fill-opacity", a.FillOpacity)
	}
	if a.FillRule != "" {
		html.Attr(sb, "fill-rule", a.FillRule)
	}
	if a.Filter != "" {
		html.Attr(sb, "filter", a.Filter)
	}
	if a.FloodColor != "" {
		html.Attr(sb, "flood-color", a.FloodColor)
	}
	if a.FloodOpacity != "" {
		html.Attr(sb, "flood-opacity", a.FloodOpacity)
	}
	if a.FontFamily != "" {
		html.Attr(sb, "font-family", a.FontFamily)
	}
	if a.FontSize != "" {
		html.Attr(sb, "font-size", a.FontSize)
	}
	if a.FontSizeAdjust != "" {
		html.Attr(sb, "font-size-adjust", a.FontSizeAdjust)
	}
	if a.FontStretch != "" {
		html.Attr(sb, "font-stretch", a.FontStretch)
	}
	if a.FontStyle != "" {
		html.Attr(sb, "font-style", a.FontStyle)
	}
	if a.FontVariant != "" {
		html.Attr(sb, "font-variant", a.FontVariant)
	}
	if a.FontWeight != "" {
		html.Attr(sb, "font-weight", a.FontWeight)
	}
	if a.GlyphOrientationHorizontal != "" {
		html.Attr(sb, "glyph-orientation-horizontal", a.GlyphOrientationHorizontal)
	}
	if a.GlyphOrientationVertical != "" {
		html.Attr(sb, "glyph-orientation-vertical", a.GlyphOrientationVertical)
	}
	if a.Href != "" {
		html.Attr(sb, "href", a.Href)
	}
	if a.ImageRendering != "" {
		html.Attr(sb, "image-rendering", a.ImageRendering)
	}
	if a.Kerning != "" {
		html.Attr(sb, "kerning", a.Kerning)
	}
	if a.LengthAdjust != "" {
		html.Attr(sb, "lengthAdjust", a.LengthAdjust)
	}
	if a.LetterSpacing != "" {
		html.Attr(sb, "letter-spacing", a.LetterSpacing)
	}
	if a.LightingColor != "" {
		html.Attr(sb, "lighting-color", a.LightingColor)
	}
	if a.MarkerEnd != "" {
		html.Attr(sb, "marker-end", a.MarkerEnd)
	}
	if a.MarkerMid != "" {
		html.Attr(sb, "marker-mid", a.MarkerMid)
	}
	if a.MarkerStart != "" {
		html.Attr(sb, "marker-start", a.MarkerStart)
	}
	if a.Mask != "" {
		html.Attr(sb, "mask", a.Mask)
	}
	if a.Method != "" {
		html.Attr(sb, "method", a.Method)
	}
	if a.Opacity != "" {
		html.Attr(sb, "opacity", a.Opacity)
	}
	if a.Overflow != "" {
		html.Attr(sb, "overflow", a.Overflow)
	}
	if a.Path != "" {
		html.Attr(sb, "path", a.Path)
	}
	if a.PointerEvents != "" {
		html.Attr(sb, "pointer-events", a.PointerEvents)
	}
	if a.RequiredExtensions != "" {
		html.Attr(sb, "requiredExtensions", a.RequiredExtensions)
	}
	if a.RequiredFeatures != "" {
		html.Attr(sb, "requiredFeatures", a.RequiredFeatures)
	}
	if a.ShapeRendering != "" {
		html.Attr(sb, "shape-rendering", a.ShapeRendering)
	}
	if a.Side != "" {
		html.Attr(sb, "side", a.Side)
	}
	if a.Spacing != "" {
		html.Attr(sb, "spacing", a.Spacing)
	}
	if a.StartOffset != "" {
		html.Attr(sb, "startOffset", a.StartOffset)
	}
	if a.StopColor != "" {
		html.Attr(sb, "stop-color", a.StopColor)
	}
	if a.StopOpacity != "" {
		html.Attr(sb, "stop-opacity", a.StopOpacity)
	}
	if a.Stroke != "" {
		html.Attr(sb, "stroke", a.Stroke)
	}
	if a.StrokeDasharray != "" {
		html.Attr(sb, "stroke-dasharray", a.StrokeDasharray)
	}
	if a.StrokeDashoffset != "" {
		html.Attr(sb, "stroke-dashoffset", a.StrokeDashoffset)
	}
	if a.StrokeLinecap != "" {
		html.Attr(sb, "stroke-linecap", a.StrokeLinecap)
	}
	if a.StrokeLinejoin != "" {
		html.Attr(sb, "stroke-linejoin", a.StrokeLinejoin)
	}
	if a.StrokeMiterlimit != "" {
		html.Attr(sb, "stroke-miterlimit", a.StrokeMiterlimit)
	}
	if a.StrokeOpacity != "" {
		html.Attr(sb, "stroke-opacity", a.StrokeOpacity)
	}
	if a.StrokeWidth != "" {
		html.Attr(sb, "stroke-width", a.StrokeWidth)
	}
	if a.SystemLanguage != "" {
		html.Attr(sb, "systemLanguage", a.SystemLanguage)
	}
	if a.TextAnchor != "" {
		html.Attr(sb, "text-anchor", a.TextAnchor)
	}
	if a.TextDecoration != "" {
		html.Attr(sb, "text-decoration", a.TextDecoration)
	}
	if a.TextLength != "" {
		html.Attr(sb, "textLength", a.TextLength)
	}
	if a.TextRendering != "" {
		html.Attr(sb, "text-rendering", a.TextRendering)
	}
	if a.UnicodeBidi != "" {
		html.Attr(sb, "unicode-bidi", a.UnicodeBidi)
	}
	if a.Visibility != "" {
		html.Attr(sb, "visibility", a.Visibility)
	}
	if a.WordSpacing != "" {
		html.Attr(sb, "word-spacing", a.WordSpacing)
	}
	if a.WritingMode != "" {
		html.Attr(sb, "writing-mode", a.WritingMode)
	}
}
