// Code generated by gen-svg; DO NOT EDIT.
package svg

import (
	"strings"

	"github.com/plainkit/html"
)

// AltGlyphItemAttrs holds the attributes for the altGlyphItem SVG element
type AltGlyphItemAttrs struct {
	html.GlobalAttrs
}

// AltGlyphItem creates an SVG altGlyphItem element
func AltGlyphItem(attrs AltGlyphItemAttrs, children ...html.Component) html.Node {
	return html.Node{
		Tag:   "altGlyphItem",
		Attrs: &attrs,
		Kids:  children,
	}
}

// writeAttrs writes the HTML attributes to the string builder
func (a *AltGlyphItemAttrs) writeAttrs(sb *strings.Builder) {
	html.WriteGlobal(sb, &a.GlobalAttrs)
}
