// Code generated by gen-svg; DO NOT EDIT.

package svg

import (
	"strings"

	"github.com/plainkit/html"
)

// FeColorMatrixAttrs holds the attributes for the feColorMatrix SVG element
type FeColorMatrixAttrs struct {
	SvgGlobal                  SvgGlobalAttrs
	AlignmentBaseline          string
	BaselineShift              string
	Clip                       string
	ClipPath                   string
	ClipRule                   string
	Color                      string
	ColorInterpolation         string
	ColorInterpolationFilters  string
	ColorProfile               string
	ColorRendering             string
	Cursor                     string
	Direction                  string
	Display                    string
	DominantBaseline           string
	EnableBackground           string
	Fill                       string
	FillOpacity                string
	FillRule                   string
	Filter                     string
	FloodColor                 string
	FloodOpacity               string
	FontFamily                 string
	FontSize                   string
	FontSizeAdjust             string
	FontStretch                string
	FontStyle                  string
	FontVariant                string
	FontWeight                 string
	GlyphOrientationHorizontal string
	GlyphOrientationVertical   string
	Height                     string
	ImageRendering             string
	In                         string
	Kerning                    string
	LetterSpacing              string
	LightingColor              string
	MarkerEnd                  string
	MarkerMid                  string
	MarkerStart                string
	Mask                       string
	Opacity                    string
	Overflow                   string
	PointerEvents              string
	Result                     string
	ShapeRendering             string
	StopColor                  string
	StopOpacity                string
	Stroke                     string
	StrokeDasharray            string
	StrokeDashoffset           string
	StrokeLinecap              string
	StrokeLinejoin             string
	StrokeMiterlimit           string
	StrokeOpacity              string
	StrokeWidth                string
	TextAnchor                 string
	TextDecoration             string
	TextRendering              string
	Type                       string
	UnicodeBidi                string
	Values                     string
	Visibility                 string
	Width                      string
	WordSpacing                string
	WritingMode                string
	X                          string
	Y                          string
}

// FeColorMatrixArg interface for feColorMatrix element arguments
type FeColorMatrixArg interface {
	applyFeColorMatrix(*FeColorMatrixAttrs, *[]html.Component)
}

// defaultFeColorMatrixAttrs creates default attributes for feColorMatrix
func defaultFeColorMatrixAttrs() *FeColorMatrixAttrs {
	return &FeColorMatrixAttrs{
		SvgGlobal: SvgGlobalAttrs{},
	}
}

// FeColorMatrix creates an SVG feColorMatrix element
func FeColorMatrix(args ...FeColorMatrixArg) html.Node {
	a := defaultFeColorMatrixAttrs()
	var kids []html.Component
	for _, ar := range args {
		ar.applyFeColorMatrix(a, &kids)
	}
	return html.Node{
		Tag:   "feColorMatrix",
		Attrs: a,
		Kids:  kids,
	}
}

// Global applies global SVG attributes to feColorMatrix
func (g Global) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	g.do(&a.SvgGlobal)
}

// AlignmentBaselineOpt applies to FeColorMatrix
func (o AlignmentBaselineOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.AlignmentBaseline = o.v
}

// BaselineShiftOpt applies to FeColorMatrix
func (o BaselineShiftOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.BaselineShift = o.v
}

// ClipOpt applies to FeColorMatrix
func (o ClipOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.Clip = o.v
}

// ClipPathOpt applies to FeColorMatrix
func (o ClipPathOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.ClipPath = o.v
}

// ClipRuleOpt applies to FeColorMatrix
func (o ClipRuleOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.ClipRule = o.v
}

// ColorOpt applies to FeColorMatrix
func (o ColorOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.Color = o.v
}

// ColorInterpolationOpt applies to FeColorMatrix
func (o ColorInterpolationOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.ColorInterpolation = o.v
}

// ColorInterpolationFiltersOpt applies to FeColorMatrix
func (o ColorInterpolationFiltersOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.ColorInterpolationFilters = o.v
}

// ColorProfileOpt applies to FeColorMatrix
func (o ColorProfileOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.ColorProfile = o.v
}

// ColorRenderingOpt applies to FeColorMatrix
func (o ColorRenderingOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.ColorRendering = o.v
}

// CursorOpt applies to FeColorMatrix
func (o CursorOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.Cursor = o.v
}

// DirectionOpt applies to FeColorMatrix
func (o DirectionOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.Direction = o.v
}

// DisplayOpt applies to FeColorMatrix
func (o DisplayOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.Display = o.v
}

// DominantBaselineOpt applies to FeColorMatrix
func (o DominantBaselineOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.DominantBaseline = o.v
}

// EnableBackgroundOpt applies to FeColorMatrix
func (o EnableBackgroundOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.EnableBackground = o.v
}

// FillOpt applies to FeColorMatrix
func (o FillOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.Fill = o.v
}

// FillOpacityOpt applies to FeColorMatrix
func (o FillOpacityOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.FillOpacity = o.v
}

// FillRuleOpt applies to FeColorMatrix
func (o FillRuleOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.FillRule = o.v
}

// FilterOpt applies to FeColorMatrix
func (o FilterOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.Filter = o.v
}

// FloodColorOpt applies to FeColorMatrix
func (o FloodColorOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.FloodColor = o.v
}

// FloodOpacityOpt applies to FeColorMatrix
func (o FloodOpacityOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.FloodOpacity = o.v
}

// FontFamilyOpt applies to FeColorMatrix
func (o FontFamilyOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.FontFamily = o.v
}

// FontSizeOpt applies to FeColorMatrix
func (o FontSizeOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.FontSize = o.v
}

// FontSizeAdjustOpt applies to FeColorMatrix
func (o FontSizeAdjustOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.FontSizeAdjust = o.v
}

// FontStretchOpt applies to FeColorMatrix
func (o FontStretchOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.FontStretch = o.v
}

// FontStyleOpt applies to FeColorMatrix
func (o FontStyleOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.FontStyle = o.v
}

// FontVariantOpt applies to FeColorMatrix
func (o FontVariantOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.FontVariant = o.v
}

// FontWeightOpt applies to FeColorMatrix
func (o FontWeightOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.FontWeight = o.v
}

// GlyphOrientationHorizontalOpt applies to FeColorMatrix
func (o GlyphOrientationHorizontalOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.GlyphOrientationHorizontal = o.v
}

// GlyphOrientationVerticalOpt applies to FeColorMatrix
func (o GlyphOrientationVerticalOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.GlyphOrientationVertical = o.v
}

// HeightOpt applies to FeColorMatrix
func (o HeightOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.Height = o.v
}

// ImageRenderingOpt applies to FeColorMatrix
func (o ImageRenderingOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.ImageRendering = o.v
}

// InOpt applies to FeColorMatrix
func (o InOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.In = o.v
}

// KerningOpt applies to FeColorMatrix
func (o KerningOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.Kerning = o.v
}

// LetterSpacingOpt applies to FeColorMatrix
func (o LetterSpacingOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.LetterSpacing = o.v
}

// LightingColorOpt applies to FeColorMatrix
func (o LightingColorOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.LightingColor = o.v
}

// MarkerEndOpt applies to FeColorMatrix
func (o MarkerEndOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.MarkerEnd = o.v
}

// MarkerMidOpt applies to FeColorMatrix
func (o MarkerMidOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.MarkerMid = o.v
}

// MarkerStartOpt applies to FeColorMatrix
func (o MarkerStartOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.MarkerStart = o.v
}

// MaskOpt applies to FeColorMatrix
func (o MaskOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.Mask = o.v
}

// OpacityOpt applies to FeColorMatrix
func (o OpacityOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.Opacity = o.v
}

// OverflowOpt applies to FeColorMatrix
func (o OverflowOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.Overflow = o.v
}

// PointerEventsOpt applies to FeColorMatrix
func (o PointerEventsOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.PointerEvents = o.v
}

// ResultOpt applies to FeColorMatrix
func (o ResultOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.Result = o.v
}

// ShapeRenderingOpt applies to FeColorMatrix
func (o ShapeRenderingOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.ShapeRendering = o.v
}

// StopColorOpt applies to FeColorMatrix
func (o StopColorOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.StopColor = o.v
}

// StopOpacityOpt applies to FeColorMatrix
func (o StopOpacityOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.StopOpacity = o.v
}

// StrokeOpt applies to FeColorMatrix
func (o StrokeOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.Stroke = o.v
}

// StrokeDasharrayOpt applies to FeColorMatrix
func (o StrokeDasharrayOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.StrokeDasharray = o.v
}

// StrokeDashoffsetOpt applies to FeColorMatrix
func (o StrokeDashoffsetOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.StrokeDashoffset = o.v
}

// StrokeLinecapOpt applies to FeColorMatrix
func (o StrokeLinecapOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.StrokeLinecap = o.v
}

// StrokeLinejoinOpt applies to FeColorMatrix
func (o StrokeLinejoinOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.StrokeLinejoin = o.v
}

// StrokeMiterlimitOpt applies to FeColorMatrix
func (o StrokeMiterlimitOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.StrokeMiterlimit = o.v
}

// StrokeOpacityOpt applies to FeColorMatrix
func (o StrokeOpacityOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.StrokeOpacity = o.v
}

// StrokeWidthOpt applies to FeColorMatrix
func (o StrokeWidthOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.StrokeWidth = o.v
}

// TextAnchorOpt applies to FeColorMatrix
func (o TextAnchorOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.TextAnchor = o.v
}

// TextDecorationOpt applies to FeColorMatrix
func (o TextDecorationOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.TextDecoration = o.v
}

// TextRenderingOpt applies to FeColorMatrix
func (o TextRenderingOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.TextRendering = o.v
}

// TypeOpt applies to FeColorMatrix
func (o TypeOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.Type = o.v
}

// UnicodeBidiOpt applies to FeColorMatrix
func (o UnicodeBidiOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.UnicodeBidi = o.v
}

// ValuesOpt applies to FeColorMatrix
func (o ValuesOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.Values = o.v
}

// VisibilityOpt applies to FeColorMatrix
func (o VisibilityOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.Visibility = o.v
}

// WidthOpt applies to FeColorMatrix
func (o WidthOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.Width = o.v
}

// WordSpacingOpt applies to FeColorMatrix
func (o WordSpacingOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.WordSpacing = o.v
}

// WritingModeOpt applies to FeColorMatrix
func (o WritingModeOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.WritingMode = o.v
}

// XOpt applies to FeColorMatrix
func (o XOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.X = o.v
}

// YOpt applies to FeColorMatrix
func (o YOpt) applyFeColorMatrix(a *FeColorMatrixAttrs, _ *[]html.Component) {
	a.Y = o.v
}

// writeAttrs writes the SVG attributes to the string builder
func (a *FeColorMatrixAttrs) writeAttrs(sb *strings.Builder) {
	WriteSvgGlobal(sb, &a.SvgGlobal)
	if a.AlignmentBaseline != "" {
		SvgAttr(sb, "alignment-baseline", a.AlignmentBaseline)
	}
	if a.BaselineShift != "" {
		SvgAttr(sb, "baseline-shift", a.BaselineShift)
	}
	if a.Clip != "" {
		SvgAttr(sb, "clip", a.Clip)
	}
	if a.ClipPath != "" {
		SvgAttr(sb, "clip-path", a.ClipPath)
	}
	if a.ClipRule != "" {
		SvgAttr(sb, "clip-rule", a.ClipRule)
	}
	if a.Color != "" {
		SvgAttr(sb, "color", a.Color)
	}
	if a.ColorInterpolation != "" {
		SvgAttr(sb, "color-interpolation", a.ColorInterpolation)
	}
	if a.ColorInterpolationFilters != "" {
		SvgAttr(sb, "color-interpolation-filters", a.ColorInterpolationFilters)
	}
	if a.ColorProfile != "" {
		SvgAttr(sb, "color-profile", a.ColorProfile)
	}
	if a.ColorRendering != "" {
		SvgAttr(sb, "color-rendering", a.ColorRendering)
	}
	if a.Cursor != "" {
		SvgAttr(sb, "cursor", a.Cursor)
	}
	if a.Direction != "" {
		SvgAttr(sb, "direction", a.Direction)
	}
	if a.Display != "" {
		SvgAttr(sb, "display", a.Display)
	}
	if a.DominantBaseline != "" {
		SvgAttr(sb, "dominant-baseline", a.DominantBaseline)
	}
	if a.EnableBackground != "" {
		SvgAttr(sb, "enable-background", a.EnableBackground)
	}
	if a.Fill != "" {
		SvgAttr(sb, "fill", a.Fill)
	}
	if a.FillOpacity != "" {
		SvgAttr(sb, "fill-opacity", a.FillOpacity)
	}
	if a.FillRule != "" {
		SvgAttr(sb, "fill-rule", a.FillRule)
	}
	if a.Filter != "" {
		SvgAttr(sb, "filter", a.Filter)
	}
	if a.FloodColor != "" {
		SvgAttr(sb, "flood-color", a.FloodColor)
	}
	if a.FloodOpacity != "" {
		SvgAttr(sb, "flood-opacity", a.FloodOpacity)
	}
	if a.FontFamily != "" {
		SvgAttr(sb, "font-family", a.FontFamily)
	}
	if a.FontSize != "" {
		SvgAttr(sb, "font-size", a.FontSize)
	}
	if a.FontSizeAdjust != "" {
		SvgAttr(sb, "font-size-adjust", a.FontSizeAdjust)
	}
	if a.FontStretch != "" {
		SvgAttr(sb, "font-stretch", a.FontStretch)
	}
	if a.FontStyle != "" {
		SvgAttr(sb, "font-style", a.FontStyle)
	}
	if a.FontVariant != "" {
		SvgAttr(sb, "font-variant", a.FontVariant)
	}
	if a.FontWeight != "" {
		SvgAttr(sb, "font-weight", a.FontWeight)
	}
	if a.GlyphOrientationHorizontal != "" {
		SvgAttr(sb, "glyph-orientation-horizontal", a.GlyphOrientationHorizontal)
	}
	if a.GlyphOrientationVertical != "" {
		SvgAttr(sb, "glyph-orientation-vertical", a.GlyphOrientationVertical)
	}
	if a.Height != "" {
		SvgAttr(sb, "height", a.Height)
	}
	if a.ImageRendering != "" {
		SvgAttr(sb, "image-rendering", a.ImageRendering)
	}
	if a.In != "" {
		SvgAttr(sb, "in", a.In)
	}
	if a.Kerning != "" {
		SvgAttr(sb, "kerning", a.Kerning)
	}
	if a.LetterSpacing != "" {
		SvgAttr(sb, "letter-spacing", a.LetterSpacing)
	}
	if a.LightingColor != "" {
		SvgAttr(sb, "lighting-color", a.LightingColor)
	}
	if a.MarkerEnd != "" {
		SvgAttr(sb, "marker-end", a.MarkerEnd)
	}
	if a.MarkerMid != "" {
		SvgAttr(sb, "marker-mid", a.MarkerMid)
	}
	if a.MarkerStart != "" {
		SvgAttr(sb, "marker-start", a.MarkerStart)
	}
	if a.Mask != "" {
		SvgAttr(sb, "mask", a.Mask)
	}
	if a.Opacity != "" {
		SvgAttr(sb, "opacity", a.Opacity)
	}
	if a.Overflow != "" {
		SvgAttr(sb, "overflow", a.Overflow)
	}
	if a.PointerEvents != "" {
		SvgAttr(sb, "pointer-events", a.PointerEvents)
	}
	if a.Result != "" {
		SvgAttr(sb, "result", a.Result)
	}
	if a.ShapeRendering != "" {
		SvgAttr(sb, "shape-rendering", a.ShapeRendering)
	}
	if a.StopColor != "" {
		SvgAttr(sb, "stop-color", a.StopColor)
	}
	if a.StopOpacity != "" {
		SvgAttr(sb, "stop-opacity", a.StopOpacity)
	}
	if a.Stroke != "" {
		SvgAttr(sb, "stroke", a.Stroke)
	}
	if a.StrokeDasharray != "" {
		SvgAttr(sb, "stroke-dasharray", a.StrokeDasharray)
	}
	if a.StrokeDashoffset != "" {
		SvgAttr(sb, "stroke-dashoffset", a.StrokeDashoffset)
	}
	if a.StrokeLinecap != "" {
		SvgAttr(sb, "stroke-linecap", a.StrokeLinecap)
	}
	if a.StrokeLinejoin != "" {
		SvgAttr(sb, "stroke-linejoin", a.StrokeLinejoin)
	}
	if a.StrokeMiterlimit != "" {
		SvgAttr(sb, "stroke-miterlimit", a.StrokeMiterlimit)
	}
	if a.StrokeOpacity != "" {
		SvgAttr(sb, "stroke-opacity", a.StrokeOpacity)
	}
	if a.StrokeWidth != "" {
		SvgAttr(sb, "stroke-width", a.StrokeWidth)
	}
	if a.TextAnchor != "" {
		SvgAttr(sb, "text-anchor", a.TextAnchor)
	}
	if a.TextDecoration != "" {
		SvgAttr(sb, "text-decoration", a.TextDecoration)
	}
	if a.TextRendering != "" {
		SvgAttr(sb, "text-rendering", a.TextRendering)
	}
	if a.Type != "" {
		SvgAttr(sb, "type", a.Type)
	}
	if a.UnicodeBidi != "" {
		SvgAttr(sb, "unicode-bidi", a.UnicodeBidi)
	}
	if a.Values != "" {
		SvgAttr(sb, "values", a.Values)
	}
	if a.Visibility != "" {
		SvgAttr(sb, "visibility", a.Visibility)
	}
	if a.Width != "" {
		SvgAttr(sb, "width", a.Width)
	}
	if a.WordSpacing != "" {
		SvgAttr(sb, "word-spacing", a.WordSpacing)
	}
	if a.WritingMode != "" {
		SvgAttr(sb, "writing-mode", a.WritingMode)
	}
	if a.X != "" {
		SvgAttr(sb, "x", a.X)
	}
	if a.Y != "" {
		SvgAttr(sb, "y", a.Y)
	}
}
