// Code generated by gen-svg; DO NOT EDIT.

package svg

import (
	"strings"

	"github.com/plainkit/html"
)

// GlyphRefAttrs holds the attributes for the glyphRef SVG element
type GlyphRefAttrs struct {
	SvgGlobal                  SvgGlobalAttrs
	AlignmentBaseline          string
	BaselineShift              string
	Clip                       string
	ClipPath                   string
	ClipRule                   string
	Color                      string
	ColorInterpolation         string
	ColorInterpolationFilters  string
	ColorProfile               string
	ColorRendering             string
	Cursor                     string
	Direction                  string
	Display                    string
	DominantBaseline           string
	Dx                         string
	Dy                         string
	EnableBackground           string
	Fill                       string
	FillOpacity                string
	FillRule                   string
	Filter                     string
	FloodColor                 string
	FloodOpacity               string
	FontFamily                 string
	FontSize                   string
	FontSizeAdjust             string
	FontStretch                string
	FontStyle                  string
	FontVariant                string
	FontWeight                 string
	Format                     string
	GlyphOrientationHorizontal string
	GlyphOrientationVertical   string
	GlyphRef                   string
	ImageRendering             string
	Kerning                    string
	LetterSpacing              string
	LightingColor              string
	MarkerEnd                  string
	MarkerMid                  string
	MarkerStart                string
	Mask                       string
	Opacity                    string
	Overflow                   string
	PointerEvents              string
	ShapeRendering             string
	StopColor                  string
	StopOpacity                string
	Stroke                     string
	StrokeDasharray            string
	StrokeDashoffset           string
	StrokeLinecap              string
	StrokeLinejoin             string
	StrokeMiterlimit           string
	StrokeOpacity              string
	StrokeWidth                string
	TextAnchor                 string
	TextDecoration             string
	TextRendering              string
	UnicodeBidi                string
	Visibility                 string
	WordSpacing                string
	WritingMode                string
	X                          string
	Y                          string
}

// GlyphRefArg interface for glyphRef element arguments
type GlyphRefArg interface {
	applyGlyphRef(*GlyphRefAttrs, *[]html.Component)
}

// defaultGlyphRefAttrs creates default attributes for glyphRef
func defaultGlyphRefAttrs() *GlyphRefAttrs {
	return &GlyphRefAttrs{
		SvgGlobal: SvgGlobalAttrs{},
	}
}

// GlyphRef creates an SVG glyphRef element
func GlyphRef(args ...GlyphRefArg) html.Node {
	a := defaultGlyphRefAttrs()
	var kids []html.Component
	for _, ar := range args {
		ar.applyGlyphRef(a, &kids)
	}
	return html.Node{
		Tag:   "glyphRef",
		Attrs: a,
		Kids:  kids,
	}
}

// Global applies global SVG attributes to glyphRef
func (g Global) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	g.do(&a.SvgGlobal)
}

// AlignmentBaselineOpt applies to GlyphRef
func (o AlignmentBaselineOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.AlignmentBaseline = o.v
}

// BaselineShiftOpt applies to GlyphRef
func (o BaselineShiftOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.BaselineShift = o.v
}

// ClipOpt applies to GlyphRef
func (o ClipOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.Clip = o.v
}

// ClipPathOpt applies to GlyphRef
func (o ClipPathOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.ClipPath = o.v
}

// ClipRuleOpt applies to GlyphRef
func (o ClipRuleOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.ClipRule = o.v
}

// ColorOpt applies to GlyphRef
func (o ColorOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.Color = o.v
}

// ColorInterpolationOpt applies to GlyphRef
func (o ColorInterpolationOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.ColorInterpolation = o.v
}

// ColorInterpolationFiltersOpt applies to GlyphRef
func (o ColorInterpolationFiltersOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.ColorInterpolationFilters = o.v
}

// ColorProfileOpt applies to GlyphRef
func (o ColorProfileOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.ColorProfile = o.v
}

// ColorRenderingOpt applies to GlyphRef
func (o ColorRenderingOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.ColorRendering = o.v
}

// CursorOpt applies to GlyphRef
func (o CursorOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.Cursor = o.v
}

// DirectionOpt applies to GlyphRef
func (o DirectionOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.Direction = o.v
}

// DisplayOpt applies to GlyphRef
func (o DisplayOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.Display = o.v
}

// DominantBaselineOpt applies to GlyphRef
func (o DominantBaselineOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.DominantBaseline = o.v
}

// DxOpt applies to GlyphRef
func (o DxOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.Dx = o.v
}

// DyOpt applies to GlyphRef
func (o DyOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.Dy = o.v
}

// EnableBackgroundOpt applies to GlyphRef
func (o EnableBackgroundOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.EnableBackground = o.v
}

// FillOpt applies to GlyphRef
func (o FillOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.Fill = o.v
}

// FillOpacityOpt applies to GlyphRef
func (o FillOpacityOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.FillOpacity = o.v
}

// FillRuleOpt applies to GlyphRef
func (o FillRuleOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.FillRule = o.v
}

// FilterOpt applies to GlyphRef
func (o FilterOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.Filter = o.v
}

// FloodColorOpt applies to GlyphRef
func (o FloodColorOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.FloodColor = o.v
}

// FloodOpacityOpt applies to GlyphRef
func (o FloodOpacityOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.FloodOpacity = o.v
}

// FontFamilyOpt applies to GlyphRef
func (o FontFamilyOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.FontFamily = o.v
}

// FontSizeOpt applies to GlyphRef
func (o FontSizeOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.FontSize = o.v
}

// FontSizeAdjustOpt applies to GlyphRef
func (o FontSizeAdjustOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.FontSizeAdjust = o.v
}

// FontStretchOpt applies to GlyphRef
func (o FontStretchOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.FontStretch = o.v
}

// FontStyleOpt applies to GlyphRef
func (o FontStyleOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.FontStyle = o.v
}

// FontVariantOpt applies to GlyphRef
func (o FontVariantOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.FontVariant = o.v
}

// FontWeightOpt applies to GlyphRef
func (o FontWeightOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.FontWeight = o.v
}

// FormatOpt applies to GlyphRef
func (o FormatOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.Format = o.v
}

// GlyphOrientationHorizontalOpt applies to GlyphRef
func (o GlyphOrientationHorizontalOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.GlyphOrientationHorizontal = o.v
}

// GlyphOrientationVerticalOpt applies to GlyphRef
func (o GlyphOrientationVerticalOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.GlyphOrientationVertical = o.v
}

// GlyphRefOpt applies to GlyphRef
func (o GlyphRefOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.GlyphRef = o.v
}

// ImageRenderingOpt applies to GlyphRef
func (o ImageRenderingOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.ImageRendering = o.v
}

// KerningOpt applies to GlyphRef
func (o KerningOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.Kerning = o.v
}

// LetterSpacingOpt applies to GlyphRef
func (o LetterSpacingOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.LetterSpacing = o.v
}

// LightingColorOpt applies to GlyphRef
func (o LightingColorOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.LightingColor = o.v
}

// MarkerEndOpt applies to GlyphRef
func (o MarkerEndOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.MarkerEnd = o.v
}

// MarkerMidOpt applies to GlyphRef
func (o MarkerMidOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.MarkerMid = o.v
}

// MarkerStartOpt applies to GlyphRef
func (o MarkerStartOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.MarkerStart = o.v
}

// MaskOpt applies to GlyphRef
func (o MaskOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.Mask = o.v
}

// OpacityOpt applies to GlyphRef
func (o OpacityOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.Opacity = o.v
}

// OverflowOpt applies to GlyphRef
func (o OverflowOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.Overflow = o.v
}

// PointerEventsOpt applies to GlyphRef
func (o PointerEventsOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.PointerEvents = o.v
}

// ShapeRenderingOpt applies to GlyphRef
func (o ShapeRenderingOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.ShapeRendering = o.v
}

// StopColorOpt applies to GlyphRef
func (o StopColorOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.StopColor = o.v
}

// StopOpacityOpt applies to GlyphRef
func (o StopOpacityOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.StopOpacity = o.v
}

// StrokeOpt applies to GlyphRef
func (o StrokeOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.Stroke = o.v
}

// StrokeDasharrayOpt applies to GlyphRef
func (o StrokeDasharrayOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.StrokeDasharray = o.v
}

// StrokeDashoffsetOpt applies to GlyphRef
func (o StrokeDashoffsetOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.StrokeDashoffset = o.v
}

// StrokeLinecapOpt applies to GlyphRef
func (o StrokeLinecapOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.StrokeLinecap = o.v
}

// StrokeLinejoinOpt applies to GlyphRef
func (o StrokeLinejoinOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.StrokeLinejoin = o.v
}

// StrokeMiterlimitOpt applies to GlyphRef
func (o StrokeMiterlimitOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.StrokeMiterlimit = o.v
}

// StrokeOpacityOpt applies to GlyphRef
func (o StrokeOpacityOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.StrokeOpacity = o.v
}

// StrokeWidthOpt applies to GlyphRef
func (o StrokeWidthOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.StrokeWidth = o.v
}

// TextAnchorOpt applies to GlyphRef
func (o TextAnchorOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.TextAnchor = o.v
}

// TextDecorationOpt applies to GlyphRef
func (o TextDecorationOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.TextDecoration = o.v
}

// TextRenderingOpt applies to GlyphRef
func (o TextRenderingOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.TextRendering = o.v
}

// UnicodeBidiOpt applies to GlyphRef
func (o UnicodeBidiOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.UnicodeBidi = o.v
}

// VisibilityOpt applies to GlyphRef
func (o VisibilityOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.Visibility = o.v
}

// WordSpacingOpt applies to GlyphRef
func (o WordSpacingOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.WordSpacing = o.v
}

// WritingModeOpt applies to GlyphRef
func (o WritingModeOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.WritingMode = o.v
}

// XOpt applies to GlyphRef
func (o XOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.X = o.v
}

// YOpt applies to GlyphRef
func (o YOpt) applyGlyphRef(a *GlyphRefAttrs, _ *[]html.Component) {
	a.Y = o.v
}

// writeAttrs writes the SVG attributes to the string builder
func (a *GlyphRefAttrs) writeAttrs(sb *strings.Builder) {
	WriteSvgGlobal(sb, &a.SvgGlobal)
	if a.AlignmentBaseline != "" {
		SvgAttr(sb, "alignment-baseline", a.AlignmentBaseline)
	}
	if a.BaselineShift != "" {
		SvgAttr(sb, "baseline-shift", a.BaselineShift)
	}
	if a.Clip != "" {
		SvgAttr(sb, "clip", a.Clip)
	}
	if a.ClipPath != "" {
		SvgAttr(sb, "clip-path", a.ClipPath)
	}
	if a.ClipRule != "" {
		SvgAttr(sb, "clip-rule", a.ClipRule)
	}
	if a.Color != "" {
		SvgAttr(sb, "color", a.Color)
	}
	if a.ColorInterpolation != "" {
		SvgAttr(sb, "color-interpolation", a.ColorInterpolation)
	}
	if a.ColorInterpolationFilters != "" {
		SvgAttr(sb, "color-interpolation-filters", a.ColorInterpolationFilters)
	}
	if a.ColorProfile != "" {
		SvgAttr(sb, "color-profile", a.ColorProfile)
	}
	if a.ColorRendering != "" {
		SvgAttr(sb, "color-rendering", a.ColorRendering)
	}
	if a.Cursor != "" {
		SvgAttr(sb, "cursor", a.Cursor)
	}
	if a.Direction != "" {
		SvgAttr(sb, "direction", a.Direction)
	}
	if a.Display != "" {
		SvgAttr(sb, "display", a.Display)
	}
	if a.DominantBaseline != "" {
		SvgAttr(sb, "dominant-baseline", a.DominantBaseline)
	}
	if a.Dx != "" {
		SvgAttr(sb, "dx", a.Dx)
	}
	if a.Dy != "" {
		SvgAttr(sb, "dy", a.Dy)
	}
	if a.EnableBackground != "" {
		SvgAttr(sb, "enable-background", a.EnableBackground)
	}
	if a.Fill != "" {
		SvgAttr(sb, "fill", a.Fill)
	}
	if a.FillOpacity != "" {
		SvgAttr(sb, "fill-opacity", a.FillOpacity)
	}
	if a.FillRule != "" {
		SvgAttr(sb, "fill-rule", a.FillRule)
	}
	if a.Filter != "" {
		SvgAttr(sb, "filter", a.Filter)
	}
	if a.FloodColor != "" {
		SvgAttr(sb, "flood-color", a.FloodColor)
	}
	if a.FloodOpacity != "" {
		SvgAttr(sb, "flood-opacity", a.FloodOpacity)
	}
	if a.FontFamily != "" {
		SvgAttr(sb, "font-family", a.FontFamily)
	}
	if a.FontSize != "" {
		SvgAttr(sb, "font-size", a.FontSize)
	}
	if a.FontSizeAdjust != "" {
		SvgAttr(sb, "font-size-adjust", a.FontSizeAdjust)
	}
	if a.FontStretch != "" {
		SvgAttr(sb, "font-stretch", a.FontStretch)
	}
	if a.FontStyle != "" {
		SvgAttr(sb, "font-style", a.FontStyle)
	}
	if a.FontVariant != "" {
		SvgAttr(sb, "font-variant", a.FontVariant)
	}
	if a.FontWeight != "" {
		SvgAttr(sb, "font-weight", a.FontWeight)
	}
	if a.Format != "" {
		SvgAttr(sb, "format", a.Format)
	}
	if a.GlyphOrientationHorizontal != "" {
		SvgAttr(sb, "glyph-orientation-horizontal", a.GlyphOrientationHorizontal)
	}
	if a.GlyphOrientationVertical != "" {
		SvgAttr(sb, "glyph-orientation-vertical", a.GlyphOrientationVertical)
	}
	if a.GlyphRef != "" {
		SvgAttr(sb, "glyphRef", a.GlyphRef)
	}
	if a.ImageRendering != "" {
		SvgAttr(sb, "image-rendering", a.ImageRendering)
	}
	if a.Kerning != "" {
		SvgAttr(sb, "kerning", a.Kerning)
	}
	if a.LetterSpacing != "" {
		SvgAttr(sb, "letter-spacing", a.LetterSpacing)
	}
	if a.LightingColor != "" {
		SvgAttr(sb, "lighting-color", a.LightingColor)
	}
	if a.MarkerEnd != "" {
		SvgAttr(sb, "marker-end", a.MarkerEnd)
	}
	if a.MarkerMid != "" {
		SvgAttr(sb, "marker-mid", a.MarkerMid)
	}
	if a.MarkerStart != "" {
		SvgAttr(sb, "marker-start", a.MarkerStart)
	}
	if a.Mask != "" {
		SvgAttr(sb, "mask", a.Mask)
	}
	if a.Opacity != "" {
		SvgAttr(sb, "opacity", a.Opacity)
	}
	if a.Overflow != "" {
		SvgAttr(sb, "overflow", a.Overflow)
	}
	if a.PointerEvents != "" {
		SvgAttr(sb, "pointer-events", a.PointerEvents)
	}
	if a.ShapeRendering != "" {
		SvgAttr(sb, "shape-rendering", a.ShapeRendering)
	}
	if a.StopColor != "" {
		SvgAttr(sb, "stop-color", a.StopColor)
	}
	if a.StopOpacity != "" {
		SvgAttr(sb, "stop-opacity", a.StopOpacity)
	}
	if a.Stroke != "" {
		SvgAttr(sb, "stroke", a.Stroke)
	}
	if a.StrokeDasharray != "" {
		SvgAttr(sb, "stroke-dasharray", a.StrokeDasharray)
	}
	if a.StrokeDashoffset != "" {
		SvgAttr(sb, "stroke-dashoffset", a.StrokeDashoffset)
	}
	if a.StrokeLinecap != "" {
		SvgAttr(sb, "stroke-linecap", a.StrokeLinecap)
	}
	if a.StrokeLinejoin != "" {
		SvgAttr(sb, "stroke-linejoin", a.StrokeLinejoin)
	}
	if a.StrokeMiterlimit != "" {
		SvgAttr(sb, "stroke-miterlimit", a.StrokeMiterlimit)
	}
	if a.StrokeOpacity != "" {
		SvgAttr(sb, "stroke-opacity", a.StrokeOpacity)
	}
	if a.StrokeWidth != "" {
		SvgAttr(sb, "stroke-width", a.StrokeWidth)
	}
	if a.TextAnchor != "" {
		SvgAttr(sb, "text-anchor", a.TextAnchor)
	}
	if a.TextDecoration != "" {
		SvgAttr(sb, "text-decoration", a.TextDecoration)
	}
	if a.TextRendering != "" {
		SvgAttr(sb, "text-rendering", a.TextRendering)
	}
	if a.UnicodeBidi != "" {
		SvgAttr(sb, "unicode-bidi", a.UnicodeBidi)
	}
	if a.Visibility != "" {
		SvgAttr(sb, "visibility", a.Visibility)
	}
	if a.WordSpacing != "" {
		SvgAttr(sb, "word-spacing", a.WordSpacing)
	}
	if a.WritingMode != "" {
		SvgAttr(sb, "writing-mode", a.WritingMode)
	}
	if a.X != "" {
		SvgAttr(sb, "x", a.X)
	}
	if a.Y != "" {
		SvgAttr(sb, "y", a.Y)
	}
}
