// Code generated by gen-svg; DO NOT EDIT.

package svg

import (
	"strings"

	"github.com/plainkit/html"
)

// TextPathAttrs holds the attributes for the textPath SVG element
type TextPathAttrs struct {
	SvgGlobal                  SvgGlobalAttrs
	AlignmentBaseline          string
	BaselineShift              string
	Clip                       string
	ClipPath                   string
	ClipRule                   string
	Color                      string
	ColorInterpolation         string
	ColorInterpolationFilters  string
	ColorProfile               string
	ColorRendering             string
	Cursor                     string
	Direction                  string
	Display                    string
	DominantBaseline           string
	EnableBackground           string
	ExternalResourcesRequired  string
	Fill                       string
	FillOpacity                string
	FillRule                   string
	Filter                     string
	FloodColor                 string
	FloodOpacity               string
	FontFamily                 string
	FontSize                   string
	FontSizeAdjust             string
	FontStretch                string
	FontStyle                  string
	FontVariant                string
	FontWeight                 string
	GlyphOrientationHorizontal string
	GlyphOrientationVertical   string
	Href                       string
	ImageRendering             string
	Kerning                    string
	LengthAdjust               string
	LetterSpacing              string
	LightingColor              string
	MarkerEnd                  string
	MarkerMid                  string
	MarkerStart                string
	Mask                       string
	Method                     string
	Opacity                    string
	Overflow                   string
	Path                       string
	PointerEvents              string
	RequiredExtensions         string
	RequiredFeatures           string
	ShapeRendering             string
	Side                       string
	Spacing                    string
	StartOffset                string
	StopColor                  string
	StopOpacity                string
	Stroke                     string
	StrokeDasharray            string
	StrokeDashoffset           string
	StrokeLinecap              string
	StrokeLinejoin             string
	StrokeMiterlimit           string
	StrokeOpacity              string
	StrokeWidth                string
	SystemLanguage             string
	TextAnchor                 string
	TextDecoration             string
	TextLength                 string
	TextRendering              string
	UnicodeBidi                string
	Visibility                 string
	WordSpacing                string
	WritingMode                string
}

// TextPathArg interface for textPath element arguments
type TextPathArg interface {
	applyTextPath(*TextPathAttrs, *[]html.Component)
}

// defaultTextPathAttrs creates default attributes for textPath
func defaultTextPathAttrs() *TextPathAttrs {
	return &TextPathAttrs{
		SvgGlobal: SvgGlobalAttrs{},
	}
}

// TextPath creates an SVG textPath element
func TextPath(args ...TextPathArg) html.Node {
	a := defaultTextPathAttrs()
	var kids []html.Component
	for _, ar := range args {
		ar.applyTextPath(a, &kids)
	}
	return html.Node{
		Tag:   "textPath",
		Attrs: a,
		Kids:  kids,
	}
}

// Global applies global SVG attributes to textPath
func (g Global) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	g.do(&a.SvgGlobal)
}

// AlignmentBaselineOpt applies to TextPath
func (o AlignmentBaselineOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.AlignmentBaseline = o.v
}

// BaselineShiftOpt applies to TextPath
func (o BaselineShiftOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.BaselineShift = o.v
}

// ClipOpt applies to TextPath
func (o ClipOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.Clip = o.v
}

// ClipPathOpt applies to TextPath
func (o ClipPathOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.ClipPath = o.v
}

// ClipRuleOpt applies to TextPath
func (o ClipRuleOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.ClipRule = o.v
}

// ColorOpt applies to TextPath
func (o ColorOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.Color = o.v
}

// ColorInterpolationOpt applies to TextPath
func (o ColorInterpolationOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.ColorInterpolation = o.v
}

// ColorInterpolationFiltersOpt applies to TextPath
func (o ColorInterpolationFiltersOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.ColorInterpolationFilters = o.v
}

// ColorProfileOpt applies to TextPath
func (o ColorProfileOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.ColorProfile = o.v
}

// ColorRenderingOpt applies to TextPath
func (o ColorRenderingOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.ColorRendering = o.v
}

// CursorOpt applies to TextPath
func (o CursorOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.Cursor = o.v
}

// DirectionOpt applies to TextPath
func (o DirectionOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.Direction = o.v
}

// DisplayOpt applies to TextPath
func (o DisplayOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.Display = o.v
}

// DominantBaselineOpt applies to TextPath
func (o DominantBaselineOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.DominantBaseline = o.v
}

// EnableBackgroundOpt applies to TextPath
func (o EnableBackgroundOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.EnableBackground = o.v
}

// ExternalResourcesRequiredOpt applies to TextPath
func (o ExternalResourcesRequiredOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.ExternalResourcesRequired = o.v
}

// FillOpt applies to TextPath
func (o FillOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.Fill = o.v
}

// FillOpacityOpt applies to TextPath
func (o FillOpacityOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.FillOpacity = o.v
}

// FillRuleOpt applies to TextPath
func (o FillRuleOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.FillRule = o.v
}

// FilterOpt applies to TextPath
func (o FilterOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.Filter = o.v
}

// FloodColorOpt applies to TextPath
func (o FloodColorOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.FloodColor = o.v
}

// FloodOpacityOpt applies to TextPath
func (o FloodOpacityOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.FloodOpacity = o.v
}

// FontFamilyOpt applies to TextPath
func (o FontFamilyOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.FontFamily = o.v
}

// FontSizeOpt applies to TextPath
func (o FontSizeOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.FontSize = o.v
}

// FontSizeAdjustOpt applies to TextPath
func (o FontSizeAdjustOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.FontSizeAdjust = o.v
}

// FontStretchOpt applies to TextPath
func (o FontStretchOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.FontStretch = o.v
}

// FontStyleOpt applies to TextPath
func (o FontStyleOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.FontStyle = o.v
}

// FontVariantOpt applies to TextPath
func (o FontVariantOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.FontVariant = o.v
}

// FontWeightOpt applies to TextPath
func (o FontWeightOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.FontWeight = o.v
}

// GlyphOrientationHorizontalOpt applies to TextPath
func (o GlyphOrientationHorizontalOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.GlyphOrientationHorizontal = o.v
}

// GlyphOrientationVerticalOpt applies to TextPath
func (o GlyphOrientationVerticalOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.GlyphOrientationVertical = o.v
}

// HrefOpt applies to TextPath
func (o HrefOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.Href = o.v
}

// ImageRenderingOpt applies to TextPath
func (o ImageRenderingOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.ImageRendering = o.v
}

// KerningOpt applies to TextPath
func (o KerningOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.Kerning = o.v
}

// LengthAdjustOpt applies to TextPath
func (o LengthAdjustOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.LengthAdjust = o.v
}

// LetterSpacingOpt applies to TextPath
func (o LetterSpacingOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.LetterSpacing = o.v
}

// LightingColorOpt applies to TextPath
func (o LightingColorOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.LightingColor = o.v
}

// MarkerEndOpt applies to TextPath
func (o MarkerEndOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.MarkerEnd = o.v
}

// MarkerMidOpt applies to TextPath
func (o MarkerMidOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.MarkerMid = o.v
}

// MarkerStartOpt applies to TextPath
func (o MarkerStartOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.MarkerStart = o.v
}

// MaskOpt applies to TextPath
func (o MaskOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.Mask = o.v
}

// MethodOpt applies to TextPath
func (o MethodOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.Method = o.v
}

// OpacityOpt applies to TextPath
func (o OpacityOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.Opacity = o.v
}

// OverflowOpt applies to TextPath
func (o OverflowOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.Overflow = o.v
}

// PathOpt applies to TextPath
func (o PathOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.Path = o.v
}

// PointerEventsOpt applies to TextPath
func (o PointerEventsOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.PointerEvents = o.v
}

// RequiredExtensionsOpt applies to TextPath
func (o RequiredExtensionsOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.RequiredExtensions = o.v
}

// RequiredFeaturesOpt applies to TextPath
func (o RequiredFeaturesOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.RequiredFeatures = o.v
}

// ShapeRenderingOpt applies to TextPath
func (o ShapeRenderingOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.ShapeRendering = o.v
}

// SideOpt applies to TextPath
func (o SideOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.Side = o.v
}

// SpacingOpt applies to TextPath
func (o SpacingOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.Spacing = o.v
}

// StartOffsetOpt applies to TextPath
func (o StartOffsetOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.StartOffset = o.v
}

// StopColorOpt applies to TextPath
func (o StopColorOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.StopColor = o.v
}

// StopOpacityOpt applies to TextPath
func (o StopOpacityOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.StopOpacity = o.v
}

// StrokeOpt applies to TextPath
func (o StrokeOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.Stroke = o.v
}

// StrokeDasharrayOpt applies to TextPath
func (o StrokeDasharrayOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.StrokeDasharray = o.v
}

// StrokeDashoffsetOpt applies to TextPath
func (o StrokeDashoffsetOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.StrokeDashoffset = o.v
}

// StrokeLinecapOpt applies to TextPath
func (o StrokeLinecapOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.StrokeLinecap = o.v
}

// StrokeLinejoinOpt applies to TextPath
func (o StrokeLinejoinOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.StrokeLinejoin = o.v
}

// StrokeMiterlimitOpt applies to TextPath
func (o StrokeMiterlimitOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.StrokeMiterlimit = o.v
}

// StrokeOpacityOpt applies to TextPath
func (o StrokeOpacityOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.StrokeOpacity = o.v
}

// StrokeWidthOpt applies to TextPath
func (o StrokeWidthOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.StrokeWidth = o.v
}

// SystemLanguageOpt applies to TextPath
func (o SystemLanguageOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.SystemLanguage = o.v
}

// TextAnchorOpt applies to TextPath
func (o TextAnchorOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.TextAnchor = o.v
}

// TextDecorationOpt applies to TextPath
func (o TextDecorationOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.TextDecoration = o.v
}

// TextLengthOpt applies to TextPath
func (o TextLengthOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.TextLength = o.v
}

// TextRenderingOpt applies to TextPath
func (o TextRenderingOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.TextRendering = o.v
}

// UnicodeBidiOpt applies to TextPath
func (o UnicodeBidiOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.UnicodeBidi = o.v
}

// VisibilityOpt applies to TextPath
func (o VisibilityOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.Visibility = o.v
}

// WordSpacingOpt applies to TextPath
func (o WordSpacingOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.WordSpacing = o.v
}

// WritingModeOpt applies to TextPath
func (o WritingModeOpt) applyTextPath(a *TextPathAttrs, _ *[]html.Component) {
	a.WritingMode = o.v
}

// writeAttrs writes the SVG attributes to the string builder
func (a *TextPathAttrs) writeAttrs(sb *strings.Builder) {
	WriteSvgGlobal(sb, &a.SvgGlobal)
	if a.AlignmentBaseline != "" {
		SvgAttr(sb, "alignment-baseline", a.AlignmentBaseline)
	}
	if a.BaselineShift != "" {
		SvgAttr(sb, "baseline-shift", a.BaselineShift)
	}
	if a.Clip != "" {
		SvgAttr(sb, "clip", a.Clip)
	}
	if a.ClipPath != "" {
		SvgAttr(sb, "clip-path", a.ClipPath)
	}
	if a.ClipRule != "" {
		SvgAttr(sb, "clip-rule", a.ClipRule)
	}
	if a.Color != "" {
		SvgAttr(sb, "color", a.Color)
	}
	if a.ColorInterpolation != "" {
		SvgAttr(sb, "color-interpolation", a.ColorInterpolation)
	}
	if a.ColorInterpolationFilters != "" {
		SvgAttr(sb, "color-interpolation-filters", a.ColorInterpolationFilters)
	}
	if a.ColorProfile != "" {
		SvgAttr(sb, "color-profile", a.ColorProfile)
	}
	if a.ColorRendering != "" {
		SvgAttr(sb, "color-rendering", a.ColorRendering)
	}
	if a.Cursor != "" {
		SvgAttr(sb, "cursor", a.Cursor)
	}
	if a.Direction != "" {
		SvgAttr(sb, "direction", a.Direction)
	}
	if a.Display != "" {
		SvgAttr(sb, "display", a.Display)
	}
	if a.DominantBaseline != "" {
		SvgAttr(sb, "dominant-baseline", a.DominantBaseline)
	}
	if a.EnableBackground != "" {
		SvgAttr(sb, "enable-background", a.EnableBackground)
	}
	if a.ExternalResourcesRequired != "" {
		SvgAttr(sb, "externalResourcesRequired", a.ExternalResourcesRequired)
	}
	if a.Fill != "" {
		SvgAttr(sb, "fill", a.Fill)
	}
	if a.FillOpacity != "" {
		SvgAttr(sb, "fill-opacity", a.FillOpacity)
	}
	if a.FillRule != "" {
		SvgAttr(sb, "fill-rule", a.FillRule)
	}
	if a.Filter != "" {
		SvgAttr(sb, "filter", a.Filter)
	}
	if a.FloodColor != "" {
		SvgAttr(sb, "flood-color", a.FloodColor)
	}
	if a.FloodOpacity != "" {
		SvgAttr(sb, "flood-opacity", a.FloodOpacity)
	}
	if a.FontFamily != "" {
		SvgAttr(sb, "font-family", a.FontFamily)
	}
	if a.FontSize != "" {
		SvgAttr(sb, "font-size", a.FontSize)
	}
	if a.FontSizeAdjust != "" {
		SvgAttr(sb, "font-size-adjust", a.FontSizeAdjust)
	}
	if a.FontStretch != "" {
		SvgAttr(sb, "font-stretch", a.FontStretch)
	}
	if a.FontStyle != "" {
		SvgAttr(sb, "font-style", a.FontStyle)
	}
	if a.FontVariant != "" {
		SvgAttr(sb, "font-variant", a.FontVariant)
	}
	if a.FontWeight != "" {
		SvgAttr(sb, "font-weight", a.FontWeight)
	}
	if a.GlyphOrientationHorizontal != "" {
		SvgAttr(sb, "glyph-orientation-horizontal", a.GlyphOrientationHorizontal)
	}
	if a.GlyphOrientationVertical != "" {
		SvgAttr(sb, "glyph-orientation-vertical", a.GlyphOrientationVertical)
	}
	if a.Href != "" {
		SvgAttr(sb, "href", a.Href)
	}
	if a.ImageRendering != "" {
		SvgAttr(sb, "image-rendering", a.ImageRendering)
	}
	if a.Kerning != "" {
		SvgAttr(sb, "kerning", a.Kerning)
	}
	if a.LengthAdjust != "" {
		SvgAttr(sb, "lengthAdjust", a.LengthAdjust)
	}
	if a.LetterSpacing != "" {
		SvgAttr(sb, "letter-spacing", a.LetterSpacing)
	}
	if a.LightingColor != "" {
		SvgAttr(sb, "lighting-color", a.LightingColor)
	}
	if a.MarkerEnd != "" {
		SvgAttr(sb, "marker-end", a.MarkerEnd)
	}
	if a.MarkerMid != "" {
		SvgAttr(sb, "marker-mid", a.MarkerMid)
	}
	if a.MarkerStart != "" {
		SvgAttr(sb, "marker-start", a.MarkerStart)
	}
	if a.Mask != "" {
		SvgAttr(sb, "mask", a.Mask)
	}
	if a.Method != "" {
		SvgAttr(sb, "method", a.Method)
	}
	if a.Opacity != "" {
		SvgAttr(sb, "opacity", a.Opacity)
	}
	if a.Overflow != "" {
		SvgAttr(sb, "overflow", a.Overflow)
	}
	if a.Path != "" {
		SvgAttr(sb, "path", a.Path)
	}
	if a.PointerEvents != "" {
		SvgAttr(sb, "pointer-events", a.PointerEvents)
	}
	if a.RequiredExtensions != "" {
		SvgAttr(sb, "requiredExtensions", a.RequiredExtensions)
	}
	if a.RequiredFeatures != "" {
		SvgAttr(sb, "requiredFeatures", a.RequiredFeatures)
	}
	if a.ShapeRendering != "" {
		SvgAttr(sb, "shape-rendering", a.ShapeRendering)
	}
	if a.Side != "" {
		SvgAttr(sb, "side", a.Side)
	}
	if a.Spacing != "" {
		SvgAttr(sb, "spacing", a.Spacing)
	}
	if a.StartOffset != "" {
		SvgAttr(sb, "startOffset", a.StartOffset)
	}
	if a.StopColor != "" {
		SvgAttr(sb, "stop-color", a.StopColor)
	}
	if a.StopOpacity != "" {
		SvgAttr(sb, "stop-opacity", a.StopOpacity)
	}
	if a.Stroke != "" {
		SvgAttr(sb, "stroke", a.Stroke)
	}
	if a.StrokeDasharray != "" {
		SvgAttr(sb, "stroke-dasharray", a.StrokeDasharray)
	}
	if a.StrokeDashoffset != "" {
		SvgAttr(sb, "stroke-dashoffset", a.StrokeDashoffset)
	}
	if a.StrokeLinecap != "" {
		SvgAttr(sb, "stroke-linecap", a.StrokeLinecap)
	}
	if a.StrokeLinejoin != "" {
		SvgAttr(sb, "stroke-linejoin", a.StrokeLinejoin)
	}
	if a.StrokeMiterlimit != "" {
		SvgAttr(sb, "stroke-miterlimit", a.StrokeMiterlimit)
	}
	if a.StrokeOpacity != "" {
		SvgAttr(sb, "stroke-opacity", a.StrokeOpacity)
	}
	if a.StrokeWidth != "" {
		SvgAttr(sb, "stroke-width", a.StrokeWidth)
	}
	if a.SystemLanguage != "" {
		SvgAttr(sb, "systemLanguage", a.SystemLanguage)
	}
	if a.TextAnchor != "" {
		SvgAttr(sb, "text-anchor", a.TextAnchor)
	}
	if a.TextDecoration != "" {
		SvgAttr(sb, "text-decoration", a.TextDecoration)
	}
	if a.TextLength != "" {
		SvgAttr(sb, "textLength", a.TextLength)
	}
	if a.TextRendering != "" {
		SvgAttr(sb, "text-rendering", a.TextRendering)
	}
	if a.UnicodeBidi != "" {
		SvgAttr(sb, "unicode-bidi", a.UnicodeBidi)
	}
	if a.Visibility != "" {
		SvgAttr(sb, "visibility", a.Visibility)
	}
	if a.WordSpacing != "" {
		SvgAttr(sb, "word-spacing", a.WordSpacing)
	}
	if a.WritingMode != "" {
		SvgAttr(sb, "writing-mode", a.WritingMode)
	}
}
