// Code generated by gen-svg; DO NOT EDIT.
package svg

import (
	"strings"

	"github.com/plainkit/html"
)

type FePointLightAttrs struct {
	html.GlobalAttrs
	X string
	Y string
	Z string
}

func FePointLight(attrs FePointLightAttrs) html.Node {
	return html.Node{Tag: "fePointLight", Attrs: &attrs, Void: true}
}

func (a *FePointLightAttrs) writeAttrs(sb *strings.Builder) {
	html.WriteGlobal(sb, &a.GlobalAttrs)
	if a.X != "" {
		html.Attr(sb, "x", a.X)
	}
	if a.Y != "" {
		html.Attr(sb, "y", a.Y)
	}
	if a.Z != "" {
		html.Attr(sb, "z", a.Z)
	}
}
