// Code generated by gen-svg; DO NOT EDIT.

package html

import (
	"strings"
)

// SvgFeSpecularLightingAttrs holds the attributes for the feSpecularLighting SVG element
type SvgFeSpecularLightingAttrs struct {
	GlobalAttrs
	In               string
	KernelUnitLength string
	SpecularConstant string
	SpecularExponent string
	SurfaceScale     string
}

// SvgFeSpecularLightingArg interface for feSpecularLighting element arguments
type SvgFeSpecularLightingArg interface {
	applyFeSpecularLighting(*SvgFeSpecularLightingAttrs, *[]Component)
}

// defaultSvgFeSpecularLightingAttrs creates default attributes for feSpecularLighting
func defaultSvgFeSpecularLightingAttrs() *SvgFeSpecularLightingAttrs {
	return &SvgFeSpecularLightingAttrs{
		GlobalAttrs: GlobalAttrs{},
	}
}

// SvgFeSpecularLighting creates an SVG feSpecularLighting element
func SvgFeSpecularLighting(args ...SvgFeSpecularLightingArg) Node {
	a := defaultSvgFeSpecularLightingAttrs()
	var kids []Component
	for _, ar := range args {
		ar.applyFeSpecularLighting(a, &kids)
	}
	return Node{
		Tag:   "feSpecularLighting",
		Attrs: a,
		Kids:  kids,
	}
}

// Global applies global SVG attributes to feSpecularLighting
func (g Global) applyFeSpecularLighting(a *SvgFeSpecularLightingAttrs, _ *[]Component) {
	g.Do(&a.GlobalAttrs)
}

// InOpt applies to FeSpecularLighting
func (o InOpt) applyFeSpecularLighting(a *SvgFeSpecularLightingAttrs, _ *[]Component) {
	a.In = o.v
}

// KernelUnitLengthOpt applies to FeSpecularLighting
func (o KernelUnitLengthOpt) applyFeSpecularLighting(a *SvgFeSpecularLightingAttrs, _ *[]Component) {
	a.KernelUnitLength = o.v
}

// SpecularConstantOpt applies to FeSpecularLighting
func (o SpecularConstantOpt) applyFeSpecularLighting(a *SvgFeSpecularLightingAttrs, _ *[]Component) {
	a.SpecularConstant = o.v
}

// SpecularExponentOpt applies to FeSpecularLighting
func (o SpecularExponentOpt) applyFeSpecularLighting(a *SvgFeSpecularLightingAttrs, _ *[]Component) {
	a.SpecularExponent = o.v
}

// SurfaceScaleOpt applies to FeSpecularLighting
func (o SurfaceScaleOpt) applyFeSpecularLighting(a *SvgFeSpecularLightingAttrs, _ *[]Component) {
	a.SurfaceScale = o.v
}

// WriteAttrs writes the SVG attributes to the string builder
func (a *SvgFeSpecularLightingAttrs) WriteAttrs(sb *strings.Builder) {
	WriteGlobal(sb, &a.GlobalAttrs)
	if a.In != "" {
		Attr(sb, "in", a.In)
	}
	if a.KernelUnitLength != "" {
		Attr(sb, "kernelUnitLength", a.KernelUnitLength)
	}
	if a.SpecularConstant != "" {
		Attr(sb, "specularConstant", a.SpecularConstant)
	}
	if a.SpecularExponent != "" {
		Attr(sb, "specularExponent", a.SpecularExponent)
	}
	if a.SurfaceScale != "" {
		Attr(sb, "surfaceScale", a.SurfaceScale)
	}
}
