// Code generated by gen-svg; DO NOT EDIT.

package html

type AccumulateOpt struct {
	v string
}

func AAccumulate(v string) AccumulateOpt {
	return AccumulateOpt{v}
}

type AdditiveOpt struct {
	v string
}

func AAdditive(v string) AdditiveOpt {
	return AdditiveOpt{v}
}

type AmplitudeOpt struct {
	v string
}

func AAmplitude(v string) AmplitudeOpt {
	return AmplitudeOpt{v}
}

type AttributeNameOpt struct {
	v string
}

func AAttributeName(v string) AttributeNameOpt {
	return AttributeNameOpt{v}
}

type AttributeTypeOpt struct {
	v string
}

func AAttributeType(v string) AttributeTypeOpt {
	return AttributeTypeOpt{v}
}

type AzimuthOpt struct {
	v string
}

func AAzimuth(v string) AzimuthOpt {
	return AzimuthOpt{v}
}

type BaseFrequencyOpt struct {
	v string
}

func ABaseFrequency(v string) BaseFrequencyOpt {
	return BaseFrequencyOpt{v}
}

type BeginOpt struct {
	v string
}

func ABegin(v string) BeginOpt {
	return BeginOpt{v}
}

type BiasOpt struct {
	v string
}

func ABias(v string) BiasOpt {
	return BiasOpt{v}
}

type ByOpt struct {
	v string
}

func ABy(v string) ByOpt {
	return ByOpt{v}
}

type CalcModeOpt struct {
	v string
}

func ACalcMode(v string) CalcModeOpt {
	return CalcModeOpt{v}
}

type ClipPathUnitsOpt struct {
	v string
}

func AClipPathUnits(v string) ClipPathUnitsOpt {
	return ClipPathUnitsOpt{v}
}

type CxOpt struct {
	v string
}

func ACx(v string) CxOpt {
	return CxOpt{v}
}

type CyOpt struct {
	v string
}

func ACy(v string) CyOpt {
	return CyOpt{v}
}

type DOpt struct {
	v string
}

func AD(v string) DOpt {
	return DOpt{v}
}

type DiffuseConstantOpt struct {
	v string
}

func ADiffuseConstant(v string) DiffuseConstantOpt {
	return DiffuseConstantOpt{v}
}

type DivisorOpt struct {
	v string
}

func ADivisor(v string) DivisorOpt {
	return DivisorOpt{v}
}

type DurOpt struct {
	v string
}

func ADur(v string) DurOpt {
	return DurOpt{v}
}

type DxOpt struct {
	v string
}

func ADx(v string) DxOpt {
	return DxOpt{v}
}

type DyOpt struct {
	v string
}

func ADy(v string) DyOpt {
	return DyOpt{v}
}

type EdgeModeOpt struct {
	v string
}

func AEdgeMode(v string) EdgeModeOpt {
	return EdgeModeOpt{v}
}

type ElevationOpt struct {
	v string
}

func AElevation(v string) ElevationOpt {
	return ElevationOpt{v}
}

type EndOpt struct {
	v string
}

func AEnd(v string) EndOpt {
	return EndOpt{v}
}

type ExponentOpt struct {
	v string
}

func AExponent(v string) ExponentOpt {
	return ExponentOpt{v}
}

type ExternalResourcesRequiredOpt struct{}

func AExternalResourcesRequired() ExternalResourcesRequiredOpt {
	return ExternalResourcesRequiredOpt{}
}

type FillOpt struct {
	v string
}

func AFill(v string) FillOpt {
	return FillOpt{v}
}

type FillOpacityOpt struct {
	v string
}

func AFillOpacity(v string) FillOpacityOpt {
	return FillOpacityOpt{v}
}

type StrokeOpt struct {
	v string
}

func AStroke(v string) StrokeOpt {
	return StrokeOpt{v}
}

type StrokeWidthOpt struct {
	v string
}

func AStrokeWidth(v string) StrokeWidthOpt {
	return StrokeWidthOpt{v}
}

type StrokeLinecapOpt struct {
	v string
}

func AStrokeLinecap(v string) StrokeLinecapOpt {
	return StrokeLinecapOpt{v}
}

type StrokeLinejoinOpt struct {
	v string
}

func AStrokeLinejoin(v string) StrokeLinejoinOpt {
	return StrokeLinejoinOpt{v}
}

type XmlnsOpt struct {
	v string
}

func AXmlns(v string) XmlnsOpt {
	return XmlnsOpt{v}
}

type FilterUnitsOpt struct {
	v string
}

func AFilterUnits(v string) FilterUnitsOpt {
	return FilterUnitsOpt{v}
}

type FloodColorOpt struct {
	v string
}

func AFloodColor(v string) FloodColorOpt {
	return FloodColorOpt{v}
}

type FloodOpacityOpt struct {
	v string
}

func AFloodOpacity(v string) FloodOpacityOpt {
	return FloodOpacityOpt{v}
}

type FromOpt struct {
	v string
}

func AFrom(v string) FromOpt {
	return FromOpt{v}
}

type FxOpt struct {
	v string
}

func AFx(v string) FxOpt {
	return FxOpt{v}
}

type FyOpt struct {
	v string
}

func AFy(v string) FyOpt {
	return FyOpt{v}
}

type GradientTransformOpt struct {
	v string
}

func AGradientTransform(v string) GradientTransformOpt {
	return GradientTransformOpt{v}
}

type GradientUnitsOpt struct {
	v string
}

func AGradientUnits(v string) GradientUnitsOpt {
	return GradientUnitsOpt{v}
}

type InOpt struct {
	v string
}

func AIn(v string) InOpt {
	return InOpt{v}
}

type In2Opt struct {
	v string
}

func AIn2(v string) In2Opt {
	return In2Opt{v}
}

type InterceptOpt struct {
	v string
}

func AIntercept(v string) InterceptOpt {
	return InterceptOpt{v}
}

type K1Opt struct {
	v string
}

func AK1(v string) K1Opt {
	return K1Opt{v}
}

type K2Opt struct {
	v string
}

func AK2(v string) K2Opt {
	return K2Opt{v}
}

type K3Opt struct {
	v string
}

func AK3(v string) K3Opt {
	return K3Opt{v}
}

type K4Opt struct {
	v string
}

func AK4(v string) K4Opt {
	return K4Opt{v}
}

type KernelMatrixOpt struct {
	v string
}

func AKernelMatrix(v string) KernelMatrixOpt {
	return KernelMatrixOpt{v}
}

type KernelUnitLengthOpt struct {
	v string
}

func AKernelUnitLength(v string) KernelUnitLengthOpt {
	return KernelUnitLengthOpt{v}
}

type KeySplinesOpt struct {
	v string
}

func AKeySplines(v string) KeySplinesOpt {
	return KeySplinesOpt{v}
}

type KeyTimesOpt struct {
	v string
}

func AKeyTimes(v string) KeyTimesOpt {
	return KeyTimesOpt{v}
}

type LengthAdjustOpt struct {
	v string
}

func ALengthAdjust(v string) LengthAdjustOpt {
	return LengthAdjustOpt{v}
}

type LimitingConeAngleOpt struct {
	v string
}

func ALimitingConeAngle(v string) LimitingConeAngleOpt {
	return LimitingConeAngleOpt{v}
}

type MarkerHeightOpt struct {
	v string
}

func AMarkerHeight(v string) MarkerHeightOpt {
	return MarkerHeightOpt{v}
}

type MarkerUnitsOpt struct {
	v string
}

func AMarkerUnits(v string) MarkerUnitsOpt {
	return MarkerUnitsOpt{v}
}

type MarkerWidthOpt struct {
	v string
}

func AMarkerWidth(v string) MarkerWidthOpt {
	return MarkerWidthOpt{v}
}

type MaskContentUnitsOpt struct {
	v string
}

func AMaskContentUnits(v string) MaskContentUnitsOpt {
	return MaskContentUnitsOpt{v}
}

type MaskUnitsOpt struct {
	v string
}

func AMaskUnits(v string) MaskUnitsOpt {
	return MaskUnitsOpt{v}
}

type ModeOpt struct {
	v string
}

func AMode(v string) ModeOpt {
	return ModeOpt{v}
}

type NumOctavesOpt struct {
	v string
}

func ANumOctaves(v string) NumOctavesOpt {
	return NumOctavesOpt{v}
}

type OffsetOpt struct {
	v string
}

func AOffset(v string) OffsetOpt {
	return OffsetOpt{v}
}

type OperatorOpt struct {
	v string
}

func AOperator(v string) OperatorOpt {
	return OperatorOpt{v}
}

type OrderOpt struct {
	v string
}

func AOrder(v string) OrderOpt {
	return OrderOpt{v}
}

type OrientOpt struct {
	v string
}

func AOrient(v string) OrientOpt {
	return OrientOpt{v}
}

type PathLengthOpt struct {
	v string
}

func APathLength(v string) PathLengthOpt {
	return PathLengthOpt{v}
}

type PatternContentUnitsOpt struct {
	v string
}

func APatternContentUnits(v string) PatternContentUnitsOpt {
	return PatternContentUnitsOpt{v}
}

type PatternTransformOpt struct {
	v string
}

func APatternTransform(v string) PatternTransformOpt {
	return PatternTransformOpt{v}
}

type PatternUnitsOpt struct {
	v string
}

func APatternUnits(v string) PatternUnitsOpt {
	return PatternUnitsOpt{v}
}

type PointsOpt struct {
	v string
}

func APoints(v string) PointsOpt {
	return PointsOpt{v}
}

type PointsAtXOpt struct {
	v string
}

func APointsAtX(v string) PointsAtXOpt {
	return PointsAtXOpt{v}
}

type PointsAtYOpt struct {
	v string
}

func APointsAtY(v string) PointsAtYOpt {
	return PointsAtYOpt{v}
}

type PointsAtZOpt struct {
	v string
}

func APointsAtZ(v string) PointsAtZOpt {
	return PointsAtZOpt{v}
}

type PreserveAlphaOpt struct{}

func APreserveAlpha() PreserveAlphaOpt {
	return PreserveAlphaOpt{}
}

type PreserveAspectRatioOpt struct {
	v string
}

func APreserveAspectRatio(v string) PreserveAspectRatioOpt {
	return PreserveAspectRatioOpt{v}
}

type PrimitiveUnitsOpt struct {
	v string
}

func APrimitiveUnits(v string) PrimitiveUnitsOpt {
	return PrimitiveUnitsOpt{v}
}

type ROpt struct {
	v string
}

func AR(v string) ROpt {
	return ROpt{v}
}

type RadiusOpt struct {
	v string
}

func ARadius(v string) RadiusOpt {
	return RadiusOpt{v}
}

type RefXOpt struct {
	v string
}

func ARefX(v string) RefXOpt {
	return RefXOpt{v}
}

type RefYOpt struct {
	v string
}

func ARefY(v string) RefYOpt {
	return RefYOpt{v}
}

type RepeatCountOpt struct {
	v string
}

func ARepeatCount(v string) RepeatCountOpt {
	return RepeatCountOpt{v}
}

type RepeatDurOpt struct {
	v string
}

func ARepeatDur(v string) RepeatDurOpt {
	return RepeatDurOpt{v}
}

type RequiredExtensionsOpt struct {
	v string
}

func ARequiredExtensions(v string) RequiredExtensionsOpt {
	return RequiredExtensionsOpt{v}
}

type RequiredFeaturesOpt struct {
	v string
}

func ARequiredFeatures(v string) RequiredFeaturesOpt {
	return RequiredFeaturesOpt{v}
}

type RestartOpt struct {
	v string
}

func ARestart(v string) RestartOpt {
	return RestartOpt{v}
}

type RotateOpt struct {
	v string
}

func ARotate(v string) RotateOpt {
	return RotateOpt{v}
}

type RxOpt struct {
	v string
}

func ARx(v string) RxOpt {
	return RxOpt{v}
}

type RyOpt struct {
	v string
}

func ARy(v string) RyOpt {
	return RyOpt{v}
}

type ScaleOpt struct {
	v string
}

func AScale(v string) ScaleOpt {
	return ScaleOpt{v}
}

type SeedOpt struct {
	v string
}

func ASeed(v string) SeedOpt {
	return SeedOpt{v}
}

type SlopeOpt struct {
	v string
}

func ASlope(v string) SlopeOpt {
	return SlopeOpt{v}
}

type SpacingOpt struct {
	v string
}

func ASpacing(v string) SpacingOpt {
	return SpacingOpt{v}
}

type SpecularConstantOpt struct {
	v string
}

func ASpecularConstant(v string) SpecularConstantOpt {
	return SpecularConstantOpt{v}
}

type SpecularExponentOpt struct {
	v string
}

func ASpecularExponent(v string) SpecularExponentOpt {
	return SpecularExponentOpt{v}
}

type SpreadMethodOpt struct {
	v string
}

func ASpreadMethod(v string) SpreadMethodOpt {
	return SpreadMethodOpt{v}
}

type StartOffsetOpt struct {
	v string
}

func AStartOffset(v string) StartOffsetOpt {
	return StartOffsetOpt{v}
}

type StdDeviationOpt struct {
	v string
}

func AStdDeviation(v string) StdDeviationOpt {
	return StdDeviationOpt{v}
}

type StitchTilesOpt struct {
	v string
}

func AStitchTiles(v string) StitchTilesOpt {
	return StitchTilesOpt{v}
}

type StopColorOpt struct {
	v string
}

func AStopColor(v string) StopColorOpt {
	return StopColorOpt{v}
}

type SurfaceScaleOpt struct {
	v string
}

func ASurfaceScale(v string) SurfaceScaleOpt {
	return SurfaceScaleOpt{v}
}

type SystemLanguageOpt struct {
	v string
}

func ASystemLanguage(v string) SystemLanguageOpt {
	return SystemLanguageOpt{v}
}

type TableValuesOpt struct {
	v string
}

func ATableValues(v string) TableValuesOpt {
	return TableValuesOpt{v}
}

type TargetXOpt struct {
	v string
}

func ATargetX(v string) TargetXOpt {
	return TargetXOpt{v}
}

type TargetYOpt struct {
	v string
}

func ATargetY(v string) TargetYOpt {
	return TargetYOpt{v}
}

type TextLengthOpt struct {
	v string
}

func ATextLength(v string) TextLengthOpt {
	return TextLengthOpt{v}
}

type ToOpt struct {
	v string
}

func ATo(v string) ToOpt {
	return ToOpt{v}
}

type ValuesOpt struct {
	v string
}

func AValues(v string) ValuesOpt {
	return ValuesOpt{v}
}

type ViewBoxOpt struct {
	v string
}

func AViewBox(v string) ViewBoxOpt {
	return ViewBoxOpt{v}
}

type XOpt struct {
	v string
}

func AX(v string) XOpt {
	return XOpt{v}
}

type X1Opt struct {
	v string
}

func AX1(v string) X1Opt {
	return X1Opt{v}
}

type X2Opt struct {
	v string
}

func AX2(v string) X2Opt {
	return X2Opt{v}
}

type XChannelSelectorOpt struct {
	v string
}

func AXChannelSelector(v string) XChannelSelectorOpt {
	return XChannelSelectorOpt{v}
}

type YOpt struct {
	v string
}

func AY(v string) YOpt {
	return YOpt{v}
}

type Y1Opt struct {
	v string
}

func AY1(v string) Y1Opt {
	return Y1Opt{v}
}

type Y2Opt struct {
	v string
}

func AY2(v string) Y2Opt {
	return Y2Opt{v}
}

type YChannelSelectorOpt struct {
	v string
}

func AYChannelSelector(v string) YChannelSelectorOpt {
	return YChannelSelectorOpt{v}
}

type ZOpt struct {
	v string
}

func AZ(v string) ZOpt {
	return ZOpt{v}
}
