// Code generated by gen-svg; DO NOT EDIT.

package html

import (
	"strings"
)

// SvgListenerAttrs holds the attributes for the listener SVG element
type SvgListenerAttrs struct {
	GlobalAttrs
	DefaultAction string
	Event         string
	Handler       string
	Observer      string
	Phase         string
	Propagate     string
	Target        string
}

// SvgListenerArg interface for listener element arguments
type SvgListenerArg interface {
	applyListener(*SvgListenerAttrs, *[]Component)
}

// defaultSvgListenerAttrs creates default attributes for listener
func defaultSvgListenerAttrs() *SvgListenerAttrs {
	return &SvgListenerAttrs{
		GlobalAttrs: GlobalAttrs{},
	}
}

// SvgListener creates an SVG listener element
func SvgListener(args ...SvgListenerArg) Node {
	a := defaultSvgListenerAttrs()
	var kids []Component
	for _, ar := range args {
		ar.applyListener(a, &kids)
	}
	return Node{
		Tag:   "listener",
		Attrs: a,
		Kids:  kids,
	}
}

// Global applies global SVG attributes to listener
func (g Global) applyListener(a *SvgListenerAttrs, _ *[]Component) {
	g.Do(&a.GlobalAttrs)
}

// DefaultActionOpt applies to Listener
func (o DefaultActionOpt) applyListener(a *SvgListenerAttrs, _ *[]Component) {
	a.DefaultAction = o.v
}

// EventOpt applies to Listener
func (o EventOpt) applyListener(a *SvgListenerAttrs, _ *[]Component) {
	a.Event = o.v
}

// HandlerOpt applies to Listener
func (o HandlerOpt) applyListener(a *SvgListenerAttrs, _ *[]Component) {
	a.Handler = o.v
}

// ObserverOpt applies to Listener
func (o ObserverOpt) applyListener(a *SvgListenerAttrs, _ *[]Component) {
	a.Observer = o.v
}

// PhaseOpt applies to Listener
func (o PhaseOpt) applyListener(a *SvgListenerAttrs, _ *[]Component) {
	a.Phase = o.v
}

// PropagateOpt applies to Listener
func (o PropagateOpt) applyListener(a *SvgListenerAttrs, _ *[]Component) {
	a.Propagate = o.v
}

// TargetOpt applies to Listener
func (o TargetOpt) applyListener(a *SvgListenerAttrs, _ *[]Component) {
	a.Target = o.v
}

// WriteAttrs writes the SVG attributes to the string builder
func (a *SvgListenerAttrs) WriteAttrs(sb *strings.Builder) {
	WriteGlobal(sb, &a.GlobalAttrs)
	if a.DefaultAction != "" {
		Attr(sb, "defaultAction", a.DefaultAction)
	}
	if a.Event != "" {
		Attr(sb, "event", a.Event)
	}
	if a.Handler != "" {
		Attr(sb, "handler", a.Handler)
	}
	if a.Observer != "" {
		Attr(sb, "observer", a.Observer)
	}
	if a.Phase != "" {
		Attr(sb, "phase", a.Phase)
	}
	if a.Propagate != "" {
		Attr(sb, "propagate", a.Propagate)
	}
	if a.Target != "" {
		Attr(sb, "target", a.Target)
	}
}
