// Code generated by gen-svg; DO NOT EDIT.

package html

import (
	"strings"
)

// SvgFeDropShadowAttrs holds the attributes for the feDropShadow SVG element
type SvgFeDropShadowAttrs struct {
	GlobalAttrs
	Dx           string
	Dy           string
	Height       string
	In           string
	Result       string
	StdDeviation string
	Width        string
	X            string
	Y            string
}

// SvgFeDropShadowArg interface for feDropShadow element arguments
type SvgFeDropShadowArg interface {
	ApplyFeDropShadow(*SvgFeDropShadowAttrs, *[]Component)
}

// defaultSvgFeDropShadowAttrs creates default attributes for feDropShadow
func defaultSvgFeDropShadowAttrs() *SvgFeDropShadowAttrs {
	return &SvgFeDropShadowAttrs{
		GlobalAttrs: GlobalAttrs{},
	}
}

// SvgFeDropShadow creates an SVG feDropShadow element
func SvgFeDropShadow(args ...SvgFeDropShadowArg) Node {
	a := defaultSvgFeDropShadowAttrs()
	var kids []Component
	for _, ar := range args {
		ar.ApplyFeDropShadow(a, &kids)
	}
	return Node{
		Tag:   "feDropShadow",
		Attrs: a,
		Kids:  kids,
	}
}

// Global applies global SVG attributes to feDropShadow
func (g Global) ApplyFeDropShadow(a *SvgFeDropShadowAttrs, _ *[]Component) {
	g.Do(&a.GlobalAttrs)
}

// DxOpt applies to FeDropShadow
func (o DxOpt) ApplyFeDropShadow(a *SvgFeDropShadowAttrs, _ *[]Component) {
	a.Dx = o.v
}

// DyOpt applies to FeDropShadow
func (o DyOpt) ApplyFeDropShadow(a *SvgFeDropShadowAttrs, _ *[]Component) {
	a.Dy = o.v
}

// HeightOpt applies to FeDropShadow
func (o HeightOpt) ApplyFeDropShadow(a *SvgFeDropShadowAttrs, _ *[]Component) {
	a.Height = o.v
}

// InOpt applies to FeDropShadow
func (o InOpt) ApplyFeDropShadow(a *SvgFeDropShadowAttrs, _ *[]Component) {
	a.In = o.v
}

// ResultOpt applies to FeDropShadow
func (o ResultOpt) ApplyFeDropShadow(a *SvgFeDropShadowAttrs, _ *[]Component) {
	a.Result = o.v
}

// StdDeviationOpt applies to FeDropShadow
func (o StdDeviationOpt) ApplyFeDropShadow(a *SvgFeDropShadowAttrs, _ *[]Component) {
	a.StdDeviation = o.v
}

// WidthOpt applies to FeDropShadow
func (o WidthOpt) ApplyFeDropShadow(a *SvgFeDropShadowAttrs, _ *[]Component) {
	a.Width = o.v
}

// XOpt applies to FeDropShadow
func (o XOpt) ApplyFeDropShadow(a *SvgFeDropShadowAttrs, _ *[]Component) {
	a.X = o.v
}

// YOpt applies to FeDropShadow
func (o YOpt) ApplyFeDropShadow(a *SvgFeDropShadowAttrs, _ *[]Component) {
	a.Y = o.v
}

// WriteAttrs writes the SVG attributes to the string builder
func (a *SvgFeDropShadowAttrs) WriteAttrs(sb *strings.Builder) {
	WriteGlobal(sb, &a.GlobalAttrs)
	if a.Dx != "" {
		Attr(sb, "dx", a.Dx)
	}
	if a.Dy != "" {
		Attr(sb, "dy", a.Dy)
	}
	if a.Height != "" {
		Attr(sb, "height", a.Height)
	}
	if a.In != "" {
		Attr(sb, "in", a.In)
	}
	if a.Result != "" {
		Attr(sb, "result", a.Result)
	}
	if a.StdDeviation != "" {
		Attr(sb, "stdDeviation", a.StdDeviation)
	}
	if a.Width != "" {
		Attr(sb, "width", a.Width)
	}
	if a.X != "" {
		Attr(sb, "x", a.X)
	}
	if a.Y != "" {
		Attr(sb, "y", a.Y)
	}
}
