// Code generated by gen-svg; DO NOT EDIT.

package html

import (
	"strings"
)

// SvgMetadataAttrs holds the attributes for the metadata SVG element
type SvgMetadataAttrs struct {
	GlobalAttrs
	RequiredExtensions string
	RequiredFeatures   string
	RequiredFonts      string
	RequiredFormats    string
	SystemLanguage     string
}

// SvgMetadataArg interface for metadata element arguments
type SvgMetadataArg interface {
	ApplyMetadata(*SvgMetadataAttrs, *[]Component)
}

// defaultSvgMetadataAttrs creates default attributes for metadata
func defaultSvgMetadataAttrs() *SvgMetadataAttrs {
	return &SvgMetadataAttrs{
		GlobalAttrs: GlobalAttrs{},
	}
}

// SvgMetadata creates an SVG metadata element
func SvgMetadata(args ...SvgMetadataArg) Node {
	a := defaultSvgMetadataAttrs()
	var kids []Component
	for _, ar := range args {
		ar.ApplyMetadata(a, &kids)
	}
	return Node{
		Tag:   "metadata",
		Attrs: a,
		Kids:  kids,
	}
}

// Global applies global SVG attributes to metadata
func (g Global) ApplyMetadata(a *SvgMetadataAttrs, _ *[]Component) {
	g.Do(&a.GlobalAttrs)
}

// RequiredExtensionsOpt applies to Metadata
func (o RequiredExtensionsOpt) ApplyMetadata(a *SvgMetadataAttrs, _ *[]Component) {
	a.RequiredExtensions = o.v
}

// RequiredFeaturesOpt applies to Metadata
func (o RequiredFeaturesOpt) ApplyMetadata(a *SvgMetadataAttrs, _ *[]Component) {
	a.RequiredFeatures = o.v
}

// RequiredFontsOpt applies to Metadata
func (o RequiredFontsOpt) ApplyMetadata(a *SvgMetadataAttrs, _ *[]Component) {
	a.RequiredFonts = o.v
}

// RequiredFormatsOpt applies to Metadata
func (o RequiredFormatsOpt) ApplyMetadata(a *SvgMetadataAttrs, _ *[]Component) {
	a.RequiredFormats = o.v
}

// SystemLanguageOpt applies to Metadata
func (o SystemLanguageOpt) ApplyMetadata(a *SvgMetadataAttrs, _ *[]Component) {
	a.SystemLanguage = o.v
}

// WriteAttrs writes the SVG attributes to the string builder
func (a *SvgMetadataAttrs) WriteAttrs(sb *strings.Builder) {
	WriteGlobal(sb, &a.GlobalAttrs)
	if a.RequiredExtensions != "" {
		Attr(sb, "requiredExtensions", a.RequiredExtensions)
	}
	if a.RequiredFeatures != "" {
		Attr(sb, "requiredFeatures", a.RequiredFeatures)
	}
	if a.RequiredFonts != "" {
		Attr(sb, "requiredFonts", a.RequiredFonts)
	}
	if a.RequiredFormats != "" {
		Attr(sb, "requiredFormats", a.RequiredFormats)
	}
	if a.SystemLanguage != "" {
		Attr(sb, "systemLanguage", a.SystemLanguage)
	}
}
